### ISSUE TITLE
Increase visibility of tabs

### ISSUE THREAD

**Issue by nblackburn** [Monokai/monokai-pro-vscode#10]
At the moment the tabs are the same colour as the editor and are difficult to make out. I think the tab background should contrast against the editor background but keep the active tab the same colour so it creates a visual indicator of their existence but also the active tab.

**Comment by Monokai** [comment]
This is by design. I tried to minimize visual clutter and give VSCode a clean look.

**Comment by nblackburn** [comment]
I would have to disagree and think the lack of separation creates more clutter.

**Comment by Monokai** [comment]
Closing it for now
