### ISSUE TITLE
Lost license key

### ISSUE THREAD

**Issue by dorianinc** [Monokai/monokai-pro-vscode#102]
So I recently got a new laptop and reinstalled Vs Code and added the Monokai Pro color pallete that I've been using for quite some time now. But it just occured to me that i accidentally deleted the email containing my registration key that i purchased a few months back. Is there anyway to get that back or do i have to purchase a new license?

**Comment by Monokai** [comment]
Please mail to `hello at monokai.pro` with your Paypal transaction details so I can help.
