### ISSUE TITLE
[feature request] support vscode highlight modified tabs feature

### ISSUE THREAD

**Issue by marnovo** [Monokai/monokai-pro-vscode#103]
vscode from version 1.29 supports (customizable) "[highlight modified tabs](https://github.com/Microsoft/vscode/issues/26284)" (by default).

They look blue (again, by default) which detracts from the consistency of the theme.

This feature request is to provide support (i.e. color consistency) for this vscode feature. You can [check this comment for the new color codes](https://github.com/Microsoft/vscode/issues/26284#issuecomment-427756092).

<img width="955" alt="screen shot 2018-11-22 at 8 27 45 pm" src="https://user-images.githubusercontent.com/15906764/48919874-b2141b00-ee95-11e8-897f-92a35d8365af.png">

**Comment by Monokai** [comment]
Added in 1.1.10

**Comment by marnovo** [comment]
Thanks, appreciated.
<img width="264" alt="screen shot 2019-02-19 at 7 59 25 pm" src="https://user-images.githubusercontent.com/15906764/53040104-e4c3b480-3480-11e9-8a74-82d3c1a31ab7.png">

**Comment by andyunleashed** [comment]
Hi, it seems that `"workbench.editor.highlightModifiedTabs": false` isn't respected by the theme.

![CleanShot 2024-01-12 at 10 42 22](https://github.com/Monokai/monokai-pro-vscode/assets/1426079/0666720a-34b1-49c5-9fc5-dfbbbeb1d982)
