### ISSUE TITLE
Activity bar is missing highlight color in the active elements

### ISSUE THREAD

**Issue by doctorsirius** [Monokai/monokai-pro-vscode#106]
Hi,

Your theme is missing the highlight color of the active icon in the activity bar.

This can be archived by using **activityBar.foreground** property, Visual Studio Code set it to pure white (#fff) to the default theme. I've set it as a temporal solution on my user settings json file under **workbench.colorCustomizations**, but would be great to have it by default in the theme.

I think that highlight is important to quickly associate the panel opened in the sidebar with the corresponding icon on the left.

Another cool thing would be to provide more consistency to the editor cursor color by setting its foreground color to the default active color you use on each theme (like the one used to highlight tabs), it can be set by using **editorCursor.foreground** also under **workbench.colorCustomizations**.

Thanks.

**Comment by Monokai** [comment]
Fixed in 1.1.10
