### ISSUE TITLE
Slight difference in background color

### ISSUE THREAD

**Issue by JeanMertz** [Monokai/monokai-pro-vscode#108]
There seems to be a slight difference in the background color when using the Monokai Pro theme (no filter).

You have to look really hard, but the dark background has a slightly less dark color around text, and in a block around the cursorline.

I tried pinpointing what was causing this using the (Chrome) "Developer Tools" debug helper, and was able to fix it in that overview, but am unable to figure out which color configuration is causing this.

I added some markings in the screenshot below to see the differences.

<img width="1078" alt="screenshot 2019-01-26 at 11 17 49" src="https://user-images.githubusercontent.com/383250/51785865-914d9780-215c-11e9-8d2a-c2faff3f2bc2.png">

**Comment by Monokai** [comment]
I'm seeing this too. And not only with Monokai Pro. This must be a bug with VSCode. Can you please post it here? https://github.com/Microsoft/vscode/issues
