### ISSUE TITLE
How to disable default icons?

### ISSUE THREAD

**Issue by bsvipas** [Monokai/monokai-pro-vscode#11]
Hi, how to disable default icons for Monokai Pro theme? Because I want to use other icons for folders/files and seems Monokai Pro reset it every time I set new icon theme.

**Comment by Monokai** [comment]
What you can do is manually select the Monokai Pro theme via preferences instead of via the command palette. Then you can override the icon theme or disable the icons altogether.

**Comment by bsvipas** [comment]
@Monokai I'm doing it via User Settings and it resets it automatically.

**Comment by bsvipas** [comment]
@Monokai I managed to do that, but with saving **User Settings** several times with different icon theme. So this still seems like a bug, because you need to do that several times instead of one. Because in first time it will reset it to default. And same happens on theme update, if I update Monokai Pro theme the icon theme will be reseted to default one. So I think better is to disable default icon theme and let the people choose if they really want it, you can write that in `README.md`. But still this is only my opinion, anyway thanks for such amazing work, I can't imagine myself with another color theme for VS Code.

**Comment by Monokai** [comment]
Yeah, it was a bit wonky. The new update (1.1.1) should solve this. I only change the icon theme along with the main theme if the icon theme actually is already one of the variants of Monokai Pro. When it's null (no icon theme defined), it won't automatically adjust anymore.

**Comment by bsvipas** [comment]
@Monokai yep it was fixed! Thanks!
