### ISSUE TITLE
Missing proper color for focused tree list items when tree list is inactive

### ISSUE THREAD

**Issue by doctorsirius** [Monokai/monokai-pro-vscode#111]
After the last update 1.31, looks like they introduced a new state for focused items on the tree list when it is inactive, the corresponding property is **list.inactiveFocusBackground** and currently it seems to be automatically set to the default Monokai Pro main highlight color which is too much for an inactive focus state.

I would like to say I'm a bit disappointed with the lack of updates to the theme, I paid for it hoping a better support, not that. Taking into consideration there are a lot of free themes out there more frequently updated and supported, have paid 10 euros for a outdated themes is quite disappointing and shows a lack of commitment with your project and your customers. If you can't continue updating it, make it free at least.

Regards.

**Comment by a77icu5** [comment]
any updates on this?

**Comment by doctorsirius** [comment]
Nop, but meanwhile you can fix it by setting the property yourself, open the preferences JSON file and include the following...

>   "workbench.colorCustomizations": {
    "list.inactiveFocusBackground": "#273136",
  },

**Comment by Monokai** [comment]
Fixed in 1.1.10
