### ISSUE TITLE
Arguments of C/C++ Function Call has wrong color

### ISSUE THREAD

**Issue by jonathanding** [Monokai/monokai-pro-vscode#115]
Unfortunately, I didn't observe that the issue #105 is fixed on my side, even though it was claimed fixed in v1.1.10.
Please see screenshots below. The arguments of the function call are still the same color (e.g. green) as the function itself. I tried all of the themes of Monokai Pro, while I typically use the Filter Spectrum).

I suspect that this is related to "scope": ["meta.function-call", ...], where the foreground color is set to 7bd88f.

![2019-02-19 10_19_12- test cpp - test - visual studio code](https://user-images.githubusercontent.com/1069667/52986176-d00c0000-3431-11e9-80f1-d6938d4184e5.png)
![2019-02-19 10_19_57- test cpp - test - visual studio code](https://user-images.githubusercontent.com/1069667/52986178-d0a49680-3431-11e9-8701-0f0466b9cec3.png)
![2019-02-19 10_20_19- test cpp - test - visual studio code](https://user-images.githubusercontent.com/1069667/52986181-d26e5a00-3431-11e9-853a-273bc43fdbc3.png)

**Comment by Monokai** [comment]
1.1.11 changed some scopes, and I got rid of `meta.function-call`. One thing I noticed is that VSCode doesn't have optimal c++ syntax definitions. Looks like Sublime Text has a more complete syntax definition set.

Anyway, how is it now for you in VSCode?

**Comment by jonathanding** [comment]
The new version seems great on my platform. Thanks for getting this fixed.
