### ISSUE TITLE
all keywords the same?

### ISSUE THREAD

**Issue by cpryland** [Monokai/monokai-pro-vscode#116]
At least for Javascript, it sure would be wonderful if _all_ the keywords could be one style: e.g., in Monokai Machine, light blue italic.

Having some keywords be that style, and others be roman/red, is somewhat jarring.

Or is there some way to easily customize?

**Comment by Gameghostify** [comment]
+1

Being able to customize/select this option would be great!

**Comment by Monokai** [comment]
The idea of Monokai Pro is that keywords, functions and variables are all styled differently, to quickly have an intuition of what's what. I think having all keywords in one color changes that core idea. So I'm afraid that's not suitable for Monokai Pro.
