### ISSUE TITLE
Underlined selectors in stylesheets (CSS & SCSS etc.)

### ISSUE THREAD

**Issue by andrewcourtice** [Monokai/monokai-pro-vscode#12]
Hi

Firstly, great work on the theme! This is by far the nicest theme I have ever used.

Perhaps this is just my personal taste but I'd like to provide feedback on 2 aspects of the theme:
1. Would it be possible to remove the underline from CSS & SCSS selectors or provide a setting to do so? Currently the selectors are underlined which makes them particularly hard to read, especially if your styles are designed around the BEM principle. See screenshot below:
![image](https://user-images.githubusercontent.com/11718453/29807550-d27b7f08-8cd7-11e7-8475-c28c27b25182.png)
2. This one is probably more-so just me being pedantic so feel free to disregard this one if no one else agrees with me on this. I love the icons included with the theme, however, would it be possible to add an icon for folders? Without the folder icon the file tree feels a little bit inconsistent.

Again, awesome work!

**Comment by Monokai** [comment]
Thanks! Fixed in 1.1.0
