### ISSUE TITLE
No italics after latest update(1.1.11)

### ISSUE THREAD

**Issue by himhimlo** [Monokai/monokai-pro-vscode#121]
After updating to 1.1.11, all the italics were gone.

**Comment by Monokai** [comment]
You're right, my bad! Fixed in 1.1.12

**Comment by schizaetrix** [comment]
Hi, I installed Monokai Pro 1.1.12 today. The italics are not working for me.

**Comment by schizaetrix** [comment]
"String" is normally italicized in the regular Monokai theme, but in Monokai Pro it is not:

Monokai Pro:
<img width="551" alt="Screenshot 2019-03-17 19 21 15" src="https://user-images.githubusercontent.com/43324984/54500476-1f3b3880-48eb-11e9-896b-e6ef1f1364d3.png">

Monokai:
<img width="549" alt="Screenshot 2019-03-17 19 27 25" src="https://user-images.githubusercontent.com/43324984/54500502-60cbe380-48eb-11e9-885b-a5d155958a94.png">

**Comment by GU5TAF** [comment]
> Monokai Pro:
> <img alt="Screenshot 2019-03-17 19 21 15" width="551" src="https://user-images.githubusercontent.com/43324984/54500476-1f3b3880-48eb-11e9-896b-e6ef1f1364d3.png">

As you can see in your screenshot, `const` is in italics so they are working. I think the other theme just has a different opinion on what should be italicized.
