### ISSUE TITLE
After purchasing still message displayed to purchase

### ISSUE THREAD

**Issue by rohyadav** [Monokai/monokai-pro-vscode#122]
Hi,

I have purchased a license but still get an popup message in vscode that you have to purchase. 

Is there an specific path where, i have to put that license key. 

And another thing, what i have know, i did not get any extra benefits after purchased. 

Thanks in advance.

**Comment by Monokai** [comment]
Hey @rohyadav, have you entered your license as per the instructions in your mail? The popup should not appear after purchase anymore.

**Comment by rohyadav** [comment]
Thanks :-)
