### ISSUE TITLE
Terminal configuration in VSCode screenshot?

### ISSUE THREAD

**Issue by schizaetrix** [Monokai/monokai-pro-vscode#125]
Hello!

I am enjoying the theme very much so far. This is more a question, not really an issue... I was wondering if anyone could tell me what terminal app / configuration is being used in the VSCode screenshot on the [website](https://www.monokai.pro/vscode/)?

I mean, how can I get terminal navigation to display as it does in the screenshot:
```
wimer ~ $ cd Monokai
wimer ~/Monokai $
```

..etc? I'm sorry if it's a dumb question, I just haven't played around with my terminal preferences much, in VSCode or in the standalone Mac app, so I don't know what options are out there. The terminal setup Wimer is using is more attractive than the out-of-the-box one I've currently got. :)

**Comment by GU5TAF** [comment]
> I was wondering if anyone could tell me what terminal app / configuration is being used in the VSCode screenshot on the [website](https://www.monokai.pro/vscode/)?

There  are a few ways to achieve something like that, tweaking your bash configs or installing an different shell and tweaking that, I would definitely suggest trying a different shell.

Two very popular choices are [fish](https://fishshell.com/) and [zsh](https://ohmyz.sh/). They offer extra features like syntax highlighting, auto suggestions and much much more. [Fish](https://fishshell.com/) seems to require a little less tweaking and is more "batteries included" if you want something easy to just try out.

You can also theme them, my favourite shell theme is definitely pure which is available for both [zsh](https://github.com/sindresorhus/pure) and [fish](https://github.com/rafaelrinaldi/pure).

**Comment by schizaetrix** [comment]
Thanks for the tip on fish! I spent more time than I probably should have, configuring things to look the way I want. The end result isn't exactly like Wimer's but I like it, and most importantly, there's syntax highlighting in the Monokai theme. :)

<img width="629" alt="Screenshot 2019-03-20 10 56 31" src="https://user-images.githubusercontent.com/43324984/54699461-0c00b680-4aff-11e9-86a2-9e0daf4c92a4.png">

**Comment by ntwb** [comment]
Woot, I love Fish and the Pure theme 💯

**Comment by ntwb** [comment]
Doh 🤦‍♂️, almost forgot, there's a Monokai Pro terminal theme available from here:
> https://github.com/Monokai/monokai-pro-sublime-text/issues/45#issuecomment-341005595
