### ISSUE TITLE
Could you set the style of "cls" used in defining classmethod to be the same as "self" in Python?

### ISSUE THREAD

**Issue by zzzJoelyang** [Monokai/monokai-pro-vscode#134]
In Python programming, when we define a class method, the first parameter usually can be written as "cls", not "self". So I hope you can modify the style of "cls", make it to be the same as that of "self" 
![image](https://user-images.githubusercontent.com/25009862/58368832-ed66d380-7f24-11e9-94b9-74510f9de25a.png)

**Comment by Monokai** [comment]
Fixed in 1.1.14
