### ISSUE TITLE
Buy license prompt dialog does not allow to buy license

### ISSUE THREAD

**Issue by janpawellek** [Monokai/monokai-pro-vscode#136]
Thank you for creating such a great theme. Every once a while the license reminder pops up:
> Thank you for evaluating Monokai Pro. Please purchase a license for extended use.

I'd like to obtain a license, however when clicking OK in the dialog it just disappears and nothing happens. It does not offer to actually buy a license.

In the developer tools it logs the following error message:
`ERR spawn /xdg-open ENOENT: Error: spawn /xdg-open ENOENT`

I'm using a Ubuntu 19.04 machine where xdg-open is installed and working. Also the same issue occurs on my Debian machine. Maybe the issue is the leading slash in front of /xdg-open?

**Comment by Monokai** [comment]
I've updated the package that I use to open URLs on different operating systems. Does it work now?

**Comment by janpawellek** [comment]
Thank you for providing the update! Yes, using v1.1.14 it works on my machine.
