### ISSUE TITLE
Color Scheme for Terminal and Vim Support ?

### ISSUE THREAD

**Issue by pandaa880** [Monokai/monokai-pro-vscode#137]
Is it possible to add this theme to my iTerm and syntax highlighting for vim ...?

**Comment by cdalvaro** [comment]
You can find in the following link the color schemes for Terminal.app and iTerm.app

https://github.com/Monokai/monokai-pro-sublime-text/issues/45

It would be nice to have the color scheme for vim too.

**Comment by pandaa880** [comment]
Thank you so much ..now i have consistent color scheme throughout my ide and terminal
