### ISSUE TITLE
VSCode: Colorization Change for VS Code C/C++ Extension Causes Misrepresented Coloration

### ISSUE THREAD

**Issue by tombresson** [Monokai/monokai-pro-vscode#139]
A [recent improvement](https://github.com/microsoft/vscode-cpptools/releases/tag/0.24.0) to the syntax colorization for the official **VS Code C/C++ Extension** has broken theming in Monokai Pro. 

As can be seen below, the _datatypes_ and the _macros,_ using version **0.24.0**,  are now themed the same color as the function definitions. 

**v0.23.1:**
![v0.23.1](https://i.imgur.com/JHAtI1R.png)

**v0.24.0:**
![v0.24.0](https://i.imgur.com/cmOsthR.png)

There is a work-around to temporarily fix the issue. This can done by disabling _Enhanced Colorization_.
![workaround](https://i.imgur.com/cLmFglq.png)

Here's some links to details around the change:
https://github.com/microsoft/vscode-cpptools/releases/tag/0.24.0
https://github.com/microsoft/vscode-cpptools/issues/230
https://github.com/microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/colorization.md

**Comment by Monokai** [comment]
Added support for Intellisense colors in 1.1.14
