### ISSUE TITLE
Cannot pay using the paypal account

### ISSUE THREAD

**Issue by SheGe** [Monokai/monokai-pro-vscode#140]
Hey,

When trying to finalize the paypal payment I'm getting following error:

![image](https://user-images.githubusercontent.com/3687447/61201905-3d247880-a6e6-11e9-8da2-c8e3e420dad3.png)

Is the paypal integration temporarily unavailable?

**Comment by Monokai** [comment]
Could be a temporary glitch. I've indeed updated the website and the payment module.

**Comment by SheGe** [comment]
Yes, it's work! Thanks
