### ISSUE TITLE
Bought the licence and deleted the email

### ISSUE THREAD

**Issue by Fapely** [Monokai/monokai-pro-vscode#142]
Hey, yeah so like in the title I bought the licence and accidentally deleted the message, so should I just buy is again (if it is possible) or can you send it to my another time? I know this is not the why to use the issue panel, but I had no contact info to do that personally.

**Comment by Monokai** [comment]
Can you please send an email with your request to hello at monokai.pro?

**Comment by Fapely** [comment]
szalonykapelusznik98@gmail.com

And thank you for replying.
