### ISSUE TITLE
Purchased License Received No Response

### ISSUE THREAD

**Issue by zsoumya** [Monokai/monokai-pro-vscode#143]
I have just purchased a license for the Monokai Pro on August 2, 2019, for VS Code using my credit card ending in 4846 (MasterCard) a few minutes back and have received no email responses yet. I have no proof of purchase other than the screenshot below and probably my credit card statement.

Mails sent to hello at monokai dot pro gets bounced back.

![thumbnail](https://user-images.githubusercontent.com/8484554/62440471-4ec5d280-b71e-11e9-88b3-f7b28ab1c8dc.png)

**Comment by Monokai** [comment]
That's strange, that mailbox should just work. Do you have a specific error that you're getting back?

Also, the emails with the license are sent out automatically. Could you please send me your email so I can figure out what's going wrong? You can use [hello at monokai.nl] instead.

**Comment by zsoumya** [comment]
Hi,
Thanks for getting back to me. I have attached the failure message but it's mostly "Sorry, we were unable to deliver your message to the following address. <hello@monokai.pro>: Unable to deliver the message after multiple retries, giving up."
My email is "zsoumya at yahoo dot com".
Regards,
Soumya

No trees were harmed while creating this message. However, a large number of electrons were terribly inconvenienced.
 

    On Monday, August 5, 2019, 03:57:03 AM EDT, Wimer Hazenberg <notifications@github.com> wrote:  
 
 
That's strange, that mailbox should just work. Do you have a specific error that you're getting back?

Also, the emails with the license are sent out automatically. Could you please send me your email so I can figure out what's going wrong? You can use [hello at monokai.nl] instead.

—
You are receiving this because you authored the thread.

Reply to this email directly, view it on GitHub, or mute the thread.

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Purchased License Received No Response · Issue #143 · Monokai/monokai-pr...

I have just purchased a license for the Monokai Pro on August 2, 2019, for VS Code using my credit card ending i...
 |

 |

 |





| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Build software better, together

GitHub is where people build software. More than 36 million people use GitHub to discover, fork, and contribute ...
 |

 |

 |





  
Sorry, we were unable to deliver your message to the following address.

<hello@monokai.pro>:
Unable to deliver message after multiple retries, giving up.

--- Below this line is a copy of the message.

DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=yahoo.com; s=s2048; t=1564992465; bh=sl3tzt2Tj3x7+RM8c1ALJW9LhcehSRMPCIlrRBl2Qok=; h=Date:From:To:In-Reply-To:References:Subject:From:Subject; b=gH8vH0PkL9fKX1TdxcHBktp2Dhfyz4mAF9Hf6jDe15QyiV1gBn4Y5FmU2qhhpDtMr13g5+AePMwrNtJpOsPLU97VzGXudS2dPqmaIVdHYRuNgaTbYeKuq/CxVtO7egdxGkdtRRQfIgf0gPjdrRO39ADDA/IovrSnzjj0xn93Efthp9ayOgfFJCIlYI3hXefvtvFJkROCb9mhS6Mde/ULmo54/6FwfL/q/NT6/LqXoSW6s1RP7apQwR09oB9+ol6rqQjz0fy3OojZjVu3kRVmg/i952XySkpAvbk99Ur6WNk9jEhtFCepHrIZDVMC8NhuanTy3vTkD3NDFXrQu3vSsw==
X-YMail-OSG: PUpQYeIVM1l2Y7DXbFvsmyje360.gLJpG9YiChBzQ5aHG9z82ha4tXyswT4EJrz
Yhub57.7WX9izbN_wcYmaT7nzTY3oO.m1WQlaGTUNMAd12N4pCBfMNMBskaeAJkK9vH3z5b0Y7m.
qb8l6du4Q4fHwVcQ8XdmpS5EAYuaonktW9ZnvZAHTwheHkZSPvrvLPNi6U8vQDRhaBf.QKF4tBc7
XlE_B3q_dd_KXt2Bp7U6wqPy7dbQl3mX96i7gHtjK.8OEvO8Li0kaRpIqezduu7Rrygeg48pcg3h
jOckpgcSSV6lfLTJwAZkTRbccXT8gss_tYvqHoVTEAm2tNVcjvQO7DJV_yfziwRN9d_QeEvZEMqK
WujCCVYV7cvYtgQfVcJKn6UAhZOJjXnTnW4dec36kLCRKf4dvsnmkyZpGsCxtAm.cwIz2Yt3rPqJ
ITibHyM8UHg41H.A30wV.VUVishdvSibB8MkekohZ.pZwIFSmp9JZ3po9W1PyX1LYkLPJhZ7N3u9
beuE56gJ5f6yE6.AQcRFuaYdY7i3ArgafTjwbeeaLarrLjf0LL.Vwz6ar.HvpzHqmcfnvrVLSsHO
L1fNeUMZIlCvwsZbwIWNQ83cfYilJQxzK31fhQFsronuUQokdCt7oi1aVg16.zHAnQyLF3J7vTrv
b3AMVf.E3SSn9oFcI2lEaQUkZRygvJ45x2DfUBiFJUzij3BOS_AlWTWBGwimtzGenyRTRq6QuH.8
gfOlVyZwD_XOLdEkwQeDIHqK4N4rRmt5X.RIj6FpIspapSllt77BRsHwSZXIW.U_5h69GZi6RPXF
EVfelj7h3_pF1lKjSNpq7avid3zh6Fj.sIvOvnFuAADKC1EVVbpgLTJGpilYF0YmgofwrElGRv85
N.T6uV8_WrRkWTDp3KtNy5C2OjTv_Bn1LqXyQsiAZixfwFe1sHSFTsy3fdt0lpTkuQWHEYRXemgv
GU_X1n2uk.1oAd1woY2tbdBhnJpLbU0rE7EylhH_cjb7OQAS6JLfFXlafOQm9twJaO.vYvLVR5wu
P6CEd1oljOgPbmRDKWgwx1gEI6rlp2fw.PAH5Ee8.QFPgpBruZMwupSYVegGtl7WnJIfQ_b4Gmjs
W3KXrFRXhcUXmCbzmDU5NPHKdvk9STYTHTMnOFc004amxtf9oqW1q9rAMnD52Hh78h4612gi2fUI
DTQwOzLVSOAAJF1HyxzpBYTHAjfp.8_2VyZOMeip4mhB4sT2MC0LNV2MbjVRj31wOwDRPfE3i1hn
idj9mwzCynJwbuzWo
Received: from sonic.gate.mail.ne1.yahoo.com by sonic308.consmr.mail.bf2.yahoo.com with HTTP; Mon, 5 Aug 2019 08:07:45 +0000
Date: Mon, 5 Aug 2019 05:07:20 +0000 (UTC)
From: Soumya Mukherjee <zsoumya@yahoo.com>
To: "hello@monokai.pro" <hello@monokai.pro>
Message-ID: <1800612019.995708.1564981640982@mail.yahoo.com>
In-Reply-To: <1919652098.548601.1564771400343@mail.yahoo.com>
References: <1919652098.548601.1564771400343.ref@mail.yahoo.com> <1919652098.548601.1564771400343@mail.yahoo.com>
Subject: Purchased License Received No Response
MIME-Version: 1.0
Content-Type: multipart/mixed; 
    boundary="----=_Part_995707_2129468683.1564981640982"
X-Mailer: WebService/1.1.14097 YMailNorrin Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.87 Safari/537.36
Content-Length: 392600

------=_Part_995707_2129468683.1564981640982
Content-Type: multipart/alternative; 
    boundary="----=_Part_995706_1987075894.1564981640925"

------=_Part_995706_1987075894.1564981640925
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

Hello,

I have just purchased a license for the Monokai Pro for VS Code using my cr=
edit card ending in 4846 (MasterCard) a few minutes back and have received =
no email responses yet. I have no proof of purchase other than the screensh=
ot below and probably my credit card statement.=C2=A0
I am presumably just being paranoid and will probably receive the license s=
oon but thought bringing to your attention cannot possibly hurt.

**Comment by zsoumya** [comment]
As per mail from Wimer Hazenberg  there seems to be an issue with Yahoo servers blocking monokai domain and licenses cannot be send to Yahoo because Yahoo users cannot receive emails from the monokai domain. Wimer has manually sent the license to me and it worked perfectly. Thanks Wimer. I am closing the issue.
