### ISSUE TITLE
File explorer indent guides and folder arrow icons misaligned

### ISSUE THREAD

**Issue by sneakyvince** [Monokai/monokai-pro-vscode#144]
Monokai Pro:

![Schermafbeelding 2019-08-08 om 21 31 03](https://user-images.githubusercontent.com/10743051/62732131-f0516a80-ba23-11e9-8abc-df09baa1e44b.png)

Default Seti icons:

![Schermafbeelding 2019-08-08 om 21 31 40](https://user-images.githubusercontent.com/10743051/62732177-03643a80-ba24-11e9-90d3-b40715424c38.png)

I guess you could just add some whitespace to either sides of the current icon to make it's width equal to that of the folder arrow used in Seti icon set.

**Comment by Monokai** [comment]
I think it would be better if we would have a guideline offset setting in VSCode itself. If I would add whitespace to all the icons, you're forced to use the tree indentation at a specific width. But you can adjust that setting in VSCode too. So there doesn't seem to be a solution to center-align the guidelines in all situations right now.

I would just turn them off :)

**Comment by sneakyvince** [comment]
> I think it would be better if we would have a guideline offset setting in VSCode itself. If I would add whitespace to all the icons, you're forced to use the tree indentation at a specific width. But you can adjust that setting in VSCode too. So there doesn't seem to be a solution to center-align the guidelines in all situations right now.
> 
> I would just turn them off :)

Could you in the mean time just make every icon equal width? It might take months before they implement such feature

**Comment by Monokai** [comment]
they are already, they're all center aligned in a 16x16 grid.
