### ISSUE TITLE
Email input during activation seems to be case sensitive

### ISSUE THREAD

**Issue by jandrewmoore** [Monokai/monokai-pro-vscode#147]
I bought my license on my phone, which tends to capitalize the first letter of form inputs. When I went to activate the extension in VS Code, I got an "invalid license" notification a few times before I thought to match the capitalization.

The email with my license info had the correct casing, but I didn't expect the extension to reject the lowercase version of my email address.

**Comment by Monokai** [comment]
In 1.1.14 I'm checking lowercased variants as well.
