### ISSUE TITLE
Don't log "MonokaiPro-VSCode 1.1.14, ©2019 Monokai " to console

### ISSUE THREAD

**Issue by mjbvz** [Monokai/monokai-pro-vscode#149]
**Repo**
1. Launch VS Code with this extension installed
1. Open developer tools in VS Code

**Bug**
See the message `MonokaiPro-VSCode 1.1.14, ©2019 Monokai ` in the developer console

**Suggestion**
Please remove this log. It is annoying to see this printed over and over agan when you are developing a VS Code extension and regularly restarting VS Code

**Comment by Monokai** [comment]
Allright, silence in 1.1.15 :)
