### ISSUE TITLE
Text offset in diffs (VS Code)

### ISSUE THREAD

**Issue by klaussner** [Monokai/monokai-pro-vscode#152]
Deleted lines in diffs are offset by a few pixels in VS Code, which can make them a little harder to read because the changes don't line up correctly. Also, the red and green backgrounds overlap because of the offset.

Monokai Pro:
![diff2](https://user-images.githubusercontent.com/1312807/64487212-d7f98900-d237-11e9-8f12-f83bc4dda400.png)

Monokai from VS Code:
![diff1](https://user-images.githubusercontent.com/1312807/64487209-d203a800-d237-11e9-9e2a-cb347786fdc1.png)

**Comment by Monokai** [comment]
fixed in 1.1.15
