### ISSUE TITLE
Need some improvement for JSON Syntax

### ISSUE THREAD

**Issue by GulajavaMinistudio** [Monokai/monokai-pro-vscode#155]
Thank you for making this theme. 
But i have some suggestion for future improvement. For example , improvement in syntax coloring when opening JSON file.

![Screenshot_2019-10-08_13-22-24](https://user-images.githubusercontent.com/11639412/66371895-d524bc00-e9ce-11e9-8f0e-79776aad591b.png)

It just look some plain white or yellow, without differences when JSON get deeper tag.

**Comment by Monokai** [comment]
I won't add different colors per nested level, the existing guidelines are perfect for determining this.
