### ISSUE TITLE
Payed but no mail or license.

### ISSUE THREAD

**Issue by Strazil001** [Monokai/monokai-pro-vscode#156]
![Schermafbeelding 2019-10-08 om 21 29 22](https://user-images.githubusercontent.com/27428540/66426715-bc3dfa00-ea12-11e9-9bbf-551b4767aaf2.png)

Hey guys, not sure if I'm in the right place for this but i paid with PayPal but never got the email. Please contact me

Best regards

**Comment by Monokai** [comment]
Apologies. Can you please mail me at hello at monokai.pro ? Then we'll figure out how to solve this.
