### ISSUE TITLE
[Icon request] Matlab

### ISSUE THREAD

**Issue by haberdashPI** [Monokai/monokai-pro-vscode#157]
Would be great to have an icon for Matlab files (*.m). There is a version of the original icon in the [public domain](https://commons.wikimedia.org/wiki/File:Matlab_Logo.png).

**Comment by haberdashPI** [comment]
I found MathWork's guidlines for the logo. It has a nice, one color version of the logo:

https://www.mathworks.com/brand/visual-design/mathworks-logo.html#membrane

**Comment by Monokai** [comment]
Added in 1.1.15
