### ISSUE TITLE
I am going to patent the air in my name and charge anyone who wants to breathe it

### ISSUE THREAD

**Issue by tatecapone** [Monokai/monokai-pro-vscode#159]
Having seen this, I am going to patent the air in my name and charge anyone who wants to breathe it ... look to try to sell something that was created by another ... guy, you have no knowledge whatsoever.

**Comment by arzg** [comment]
> It has been designed by the author of the original Monokai colors.

**Comment by tatecapone** [comment]
oh, I really feel my stupidity ...sorry

**Comment by Monokai** [comment]
Let's just say this issue is resolved :)
