### ISSUE TITLE
Python syntax highlighting

### ISSUE THREAD

**Issue by ajitid** [Monokai/monokai-pro-vscode#16]
Function call isn't colored in Python,

In C:
![screenshot from 2017-08-31 06-37-21](https://user-images.githubusercontent.com/26769888/29901863-26ebb846-8e18-11e7-97c5-8538c5c228d2.png)

In Python:
![screenshot from 2017-08-31 06-38-11](https://user-images.githubusercontent.com/26769888/29901866-2edcaf88-8e18-11e7-9e40-7ae1c3eaa888.png)
![screenshot from 2017-08-31 06-44-11](https://user-images.githubusercontent.com/26769888/29901869-323ff8b0-8e18-11e7-927f-316e32cecbc3.png)

--------------------------------

Color of `self` in function argument doesn't matches with `self` in `self.a`
![screenshot from 2017-08-31 06-49-06](https://user-images.githubusercontent.com/26769888/29901975-db65995e-8e18-11e7-9e41-fcd88588a337.png)
![screenshot from 2017-08-31 06-49-58](https://user-images.githubusercontent.com/26769888/29901985-ea3a3cd2-8e18-11e7-90b1-5a4eab0c095b.png)

**Comment by Monokai** [comment]
fixed in 1.1.1
