### ISSUE TITLE
Use Github Sponsors or Patreon

### ISSUE THREAD

**Issue by GulajavaMinistudio** [Monokai/monokai-pro-vscode#161]
If you want more support from community, you can activate Github Sponsors or Patreon. So your theme will be free, but with more donations and respect from community. You can take a look example from Material Theme and Material Icon Theme, or One Dark Pro Theme.

**Comment by tmarkovski** [comment]
Github Sponsors or Patreon might bring in more cash as it's not limited to the license amount, in addition to monthly sponsorships. However, that might not add up to what currently licensing brings in. Curious to see if anyone with experience using these methods thinks.

Btw, thanks for the awesome theme.

**Comment by GulajavaMinistudio** [comment]
And dont forget to make this Monokai Pro theme Open Source, with its icon theme too. So more contributors involved in this development and bug fixing. And prevent this theme become "abandonware project" that left behind by its developers.

**Comment by Monokai** [comment]
Thanks for the suggestion, but I'm leaving the licensing system as it is. What I've read so far about sponsoring open-source code via Patreon is just that it doesn't work that well in practice. If you have good examples proving otherwise, please let me know.
