### ISSUE TITLE
Support optional chaining syntax highlighting

### ISSUE THREAD

**Issue by joshua-turner** [Monokai/monokai-pro-vscode#162]
[Optional chaining](https://github.com/tc39/proposal-optional-chaining) has been supported by since RN 0.56 and VS Code 1.41.

``` js
const a = {
  b: {
    c: {
      d: true,
    },
  },
}

const workingSyntaxHighlighting = () => (
  <div>{a.b.c.d && <span>broken</span>}</div>
)

workingSyntaxHighlighting()

const brokenSyntaxHighlighting = () => (
  <div>{a?.b?.c?.d && <span>broken</span>}</div>
)

brokenSyntaxHighlighting()
```

<img width="629" alt="Screen Shot 2019-12-19 at 6 09 07 PM" src="https://user-images.githubusercontent.com/2513511/71219500-dd309000-228a-11ea-9e6b-e1d282c23691.png">

**Comment by Monokai** [comment]
Good catch. Unfortunately, this is something that has to be handled by the syntax parser and is not something that my color theme can control.
