### ISSUE TITLE
Where is icons folder with icons?

### ISSUE THREAD

**Issue by rediffusion** [Monokai/monokai-pro-vscode#163]
Hi dear friend! 10x for your theme. But I'm looking for icons to feel them. I only found a folder of files `.json`, `.woff`:

> C:\Users\MyPC\\.vscode\extensions\monokai.theme-monokai-pro-vscode-1.1.14\icon-themes\

 Best regards! 

![Emoji-19-512](https://user-images.githubusercontent.com/30071027/71527744-c377f400-28ed-11ea-9caf-0d3dd0cdd394.png)

**Comment by Monokai** [comment]
The icons are part of the theme. They appear when you select the theme via `Monokai Pro: select theme`

**Comment by rediffusion** [comment]
@Monokai 

Hi ✋
How can I convert `monokai_pro_icons.woff` to VSG? I guess there are inside all icons, am I right?
