### ISSUE TITLE
Add file icon for Dart/Flutter?

### ISSUE THREAD

**Issue by bryanrieger** [Monokai/monokai-pro-vscode#164]
I went to add an icon for Dart/Flutter files only to realise the icons are contained in a .woff font file (can't be reasonably edited), with the definitions provided in a corresponding .json file. Ideally it would be possible to add/modify icons as required, but as there is no original .glyphs or .ufo source file(s) available the only recourse is to ask you to add them.

**Comment by Monokai** [comment]
added in 1.1.15
