### ISSUE TITLE
[Icon] Folder icons instead of arrow (state sentensive: outlined and filled)

### ISSUE THREAD

**Issue by joshuabeny1999** [Monokai/monokai-pro-vscode#165]
I switched now from Material Theme and try out now Monokai Pro, because they made bad decisions with the new color scheme. I like it so far. 

But what i really liked from the Material themes are the folder icons.

If a folder is open, there is a icon with an outlined folder with an other color and if it closed it is a filled folder.

See also screenshot:
![Screenshot 2020-01-09 at 12 02 53](https://user-images.githubusercontent.com/55023662/72062381-fcde3580-32d7-11ea-8d67-d59cba771a24.png)

I would love if you implement this.

**Comment by Monokai** [comment]
The folder icons of this theme are minimal arrows. A right pointing arrow when closed and a down pointing arrow when open. I think it looks cleaner.

**Comment by joshuabeny1999** [comment]
Yeah. In the meantime I find it also better and cleaner.
