### ISSUE TITLE
Adopt the new extensionKind attribute format in package.json 

### ISSUE THREAD

**Issue by egamma** [Monokai/monokai-pro-vscode#166]
As of VS Code 1.40 the extensionKind attribute in the package.json of the extension can be an array, pls see the [documentation](https://code.visualstudio.com/api/advanced-topics/remote-extensions#incorrect-execution-location).

In your current extension the old format `"extensionkind: "ui"` is used. We will be deprecating the string type for the extensionKind property in favour of string array type.

The extensionKind attribute for this extension should be set to ["ui", "workspace"]. Indicating that the can run locally and remotely in that order.

**Comment by Monokai** [comment]
Fixed in 1.1.15. Thanks for letting me know.

**Comment by egamma** [comment]
@Monokai thank you!
