### ISSUE TITLE
Is there a way to  change the indent of the file icons?

### ISSUE THREAD

**Issue by scorcher24** [Monokai/monokai-pro-vscode#168]
I love this theme. One thing mildly annoys me though and that is the tight indent of the file view. Especially with Python and the package files `__init__.py`:
![image](https://user-images.githubusercontent.com/5300269/74512455-95378d80-4f08-11ea-904b-d96af389a806.png)

Can you please give us an option that I can set in `settings.json` in the workspace or any other method does not require me becoming a maintainer of this theme, so I can make the indent larger? :) I want to clearly see which file belongs into which folder. I have some eye sight issues.

Thanks for reading.

**Comment by Monokai** [comment]
You can set the tree indent of VSCode to 16 pixels so they match up with the icon size.

**Comment by scorcher24** [comment]
Thanks, didn't see that setting.
