### ISSUE TITLE
Debug toolbar transparency with Octagon filter

### ISSUE THREAD

**Issue by nico29** [Monokai/monokai-pro-vscode#17]
The tabs below the debug toolbar are visible, and it makes the debug options difficult to use.

![untitled](https://user-images.githubusercontent.com/3858041/29915753-0b18feba-8e3d-11e7-93e4-7be87aac9b66.png)

Thanks.

**Comment by ajitid** [comment]
It happens with default one too

**Comment by Monokai** [comment]
Fixed in 1.1.1.
