### ISSUE TITLE
Missing highlight bar between #%% in python files

### ISSUE THREAD

**Issue by idlesilver** [Monokai/monokai-pro-vscode#173]
When python file is treated as an ipynb file, what I mean, the condition using `#%%` to divide plain .py file into cells, the default style has highlight bar between cells, but these monokai styles miss this. 
![image_40](https://user-images.githubusercontent.com/47479230/76138131-91b6a280-607f-11ea-8682-cb4646803674.png)
![image_41](https://user-images.githubusercontent.com/47479230/76138133-94b19300-607f-11ea-828f-bb38d25361d8.png)

**Comment by Monokai** [comment]
Unfortunately setting a color to that line also affects the border color around the currently selected line in the editor. I've filed an issue here: https://github.com/microsoft/vscode/issues/99425
