### ISSUE TITLE
Different colors from official screenshots

### ISSUE THREAD

**Issue by vitoravelino** [Monokai/monokai-pro-vscode#174]
Is it just here that the colors are different from the official screenshots of the website/marketplace?

VSCode:
![Screenshot_4](https://user-images.githubusercontent.com/188554/76747531-0cef1700-6758-11ea-9a76-bba14163548c.png)

Website/Marketplace:
![Screenshot_3](https://user-images.githubusercontent.com/188554/76747370-c8637b80-6757-11ea-99e7-52f7ab499576.png)

Settings:

```
"workbench.colorTheme": "Monokai Pro",
```

**Comment by monotykamary** [comment]
That's probably because VSCode 1.43 introduced semantic highlighting that affects all themes.

![image](https://user-images.githubusercontent.com/1130103/76778961-3aca6f00-67dd-11ea-8c9e-1bafcb73ed46.png)

**Comment by vitoravelino** [comment]
Indeed unchecking that option makes it much closer to the screenshot but not identical. Anyway, thanks for clarifying that. :)

![Screenshot_5](https://user-images.githubusercontent.com/188554/76787295-7c382b80-6797-11ea-9df9-c6e5ee16e662.png)
