### ISSUE TITLE
Don't seem to have received "license" key

### ISSUE THREAD

**Issue by munrodnz** [Monokai/monokai-pro-vscode#178]
I paid for Monokai Pro on the 30th of March 2020 and don't seem to have received my license key or any instructions to stop the pop-up happening. I have my PayPal receipt and no other emails and have checked my Junk and Spam folders as well. Can you send me the details again please?
Cheers Darryl

**Comment by munrodnz** [comment]
Do you have any feedback here? I still haven't received any instructions on enabling the use of Monokai Pro....

**Comment by Monokai** [comment]
Hey @munrodnz could you please mail me at hello at monokai.pro and we'll quickly sort it out.
