### ISSUE TITLE
Missing markdown highlighting

### ISSUE THREAD

**Issue by ivancuric** [Monokai/monokai-pro-vscode#18]
The only syntax highlighting going on in markdown is the one for headings. 
Would be nice if you could do the rest.

**Comment by Monokai** [comment]
Should capture way more actually. Can you post a snippet that I can test?

**Comment by ivancuric** [comment]
My bad, just tested it on the demo text from https://markdown-it.github.io/

The only thing I found missing was the `>` quote indicator and list item indicators.

**Comment by Monokai** [comment]
If I remember correctly that was more a problem of the language definition itself. It couldn't apply the right scopes on the right markdown elements.

**Comment by rkpatel33** [comment]
I just ran into the same issue, my markdown looks like this:

![image](https://user-images.githubusercontent.com/3799489/32637280-bcd982fc-c56d-11e7-8a76-9f853ffc5b1b.png)

Is there a way to fix it, or any idea on what I am doing wrong?
