### ISSUE TITLE
Support for Python type hints

### ISSUE THREAD

**Issue by amitkparekh** [Monokai/monokai-pro-vscode#181]
Love Monokai Pro. On VS Code, it fails to show the type hints properly for Python code. 

It seems that VSCode uses [MagicPython](https://marketplace.visualstudio.com/items?itemName=magicstack.MagicPython) for syntax highlighting.

Is it possible for this to be added to the theme?

**Comment by Monokai** [comment]
Can you give an example of what you'd like to see? I've installed MagicPython and it looks like it picks up the highlighting.

**Comment by amitkparekh** [comment]
It wasn't working when I made the issue but it appears to be working now? I'll reopen if it occurs again.
