### ISSUE TITLE
Not suitable color when using Microsoft Remote Development extension

### ISSUE THREAD

**Issue by himhimlo** [Monokai/monokai-pro-vscode#182]
Normal:
![image](https://user-images.githubusercontent.com/3815971/79733576-ee1c0b80-8327-11ea-8f90-96abc5cd73d6.png)
Mouse hover:
![image](https://user-images.githubusercontent.com/3815971/79733535-de9cc280-8327-11ea-9f03-8aeb0a3c71d4.png)
The icon totally disappeared when mouse hover.
Thanks.

**Comment by Monokai** [comment]
Fixed in 1.1.16
