### ISSUE TITLE
Remote-WSL hover color

### ISSUE THREAD

**Issue by groveld** [Monokai/monokai-pro-vscode#187]
The Remote-WSL button in the bottom left disappears if i hover my mouse over it.
The color changes to the same color as everything else in the status bar, but the icon doesn't change to a contrasting color.

![Remote-WSL-hover](https://user-images.githubusercontent.com/3328493/80471787-3056d580-8944-11ea-9dd4-acef1c828c13.png)

**Comment by Monokai** [comment]
Fixed in 1.1.16

**Comment by groveld** [comment]
Looks good, Thanks!
