### ISSUE TITLE
No TODO, FIXME highlighting

### ISSUE THREAD

**Issue by ajitid** [Monokai/monokai-pro-vscode#19]
Monokai Pro:
![screenshot from 2017-09-01 19-31-01](https://user-images.githubusercontent.com/26769888/29973250-94aeeb3e-8f4c-11e7-927f-717d6af82d33.png)

Dark/Dark+ (default):
![screenshot from 2017-09-01 19-32-43](https://user-images.githubusercontent.com/26769888/29973267-a375a4d2-8f4c-11e7-8e79-a68929e97b3f.png)

**Comment by Monokai** [comment]
Didn't make the cut in 1.1.1, but I'll put it on the list for the next one.

**Comment by Monokai** [comment]
Fixed in 1.1.2 for Python

**Comment by nikitavoloboev** [comment]
Is it possible to also make this work for `.go` files too?
