### ISSUE TITLE
Didn't get the mail with license

### ISSUE THREAD

**Issue by alexhwan** [Monokai/monokai-pro-vscode#191]
Hi. I bought the license for monokai.pro, but didn't get any mail. Could you please check?
Sent 2 emails to hello at monokai.pro with no response.

**Comment by Monokai** [comment]
Hey, could you please mail me at hello at monokai.pro with your transaction ID or email address? Then I'll solve it for you.

**Comment by alexhwan** [comment]
Thanks.

You already solved it :)

**Comment by Monokai** [comment]
Aha, closing then :)
