### ISSUE TITLE
Request: a more darker version

### ISSUE THREAD

**Issue by enzime4u** [Monokai/monokai-pro-vscode#192]
I like the Monokai theme a lot, it is possible to get a even dark-blue version of it ? 
Thank you

**Comment by Gameghostify** [comment]
Duplicate of #180 

An even darker theme would be amazing

**Comment by barmadrid** [comment]
I agree!

I like the Filter Spectrum variant the best so I spent the last few weeks developing a slightly higher contrast version based on the Filter Spectrum variant... managed to select the color shades so far!

**Comment by enzime4u** [comment]
Actually I was looking for a new  Filter  from Monokai , trying to keep the synthax the same but pivoting to a more Dark Blue version of background, shadows etc ...

**Comment by Monokai** [comment]
Not for now :)
