### ISSUE TITLE
License not working

### ISSUE THREAD

**Issue by arcadia168** [Monokai/monokai-pro-vscode#195]
Hi, 

I bought a license to Monokai Pro but recieve this error when entering the license details from the email directly:

<img width="324" alt="Screenshot 2020-05-21 14 11 32" src="https://user-images.githubusercontent.com/6985916/82562536-54858b00-9b6d-11ea-806f-7f259f60ea16.png">

PayPal Transaction ID: Transaction ID: 8AA631198E422193J
Email address: erin.eland.168@icloud.com

Please advise.

**Comment by Monokai** [comment]
I've emailed you.
