### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by PedroFumero** [Monokai/monokai-pro-vscode#198]
I see that many people ask questions (even I did several days ago), and nobody gets answers. Does anyone know if this project has been abandoned?

If the project no longer has support, it would be worth changing to another theme, in which case which one do you recommend?

**Comment by barmadrid** [comment]
@PedroFumero I hope it's not. I agree there's some delay in addressing the issues...could be due to what's going recently!

Anyway, I am developing a **slightly** higher contrast version based on the Filter Spectrum variant... will see how it goes in the future.

**Comment by PedroFumero** [comment]
@barmadrid it sounds good, when you launch your project let me know. Regards

**Comment by Monokai** [comment]
Far from dead, but I cannot always react as fast as I would like. Anyway, just released 1.1.6!
