### ISSUE TITLE
Icons misaligned

### ISSUE THREAD

**Issue by Tyriar** [Monokai/monokai-pro-vscode#2]
<img width="122" alt="screen shot 2017-08-21 at 10 06 35 am" src="https://user-images.githubusercontent.com/2193314/29530405-7a83e072-8658-11e7-974b-bd3239268432.png">

**Comment by Tyriar** [comment]
<img width="56" alt="screen shot 2017-08-21 at 10 07 18 am" src="https://user-images.githubusercontent.com/2193314/29530416-899a0dc0-8658-11e7-9110-cabc3eb80c01.png">

**Comment by Monokai** [comment]
Good catch. I adjusted the alignment in 1.1.0
