### ISSUE TITLE
Missing "added" git file status color in explorer

### ISSUE THREAD

**Issue by nqnuv** [Monokai/monokai-pro-vscode#202]
Hi. I noticed that vscode uses default color for the "added" git file status in explorer, when git decorations are enabled in settings.
I guess it's because `gitDecoration.addedResourceForeground` color isn't specified in the theme files.

![pic1](https://user-images.githubusercontent.com/47793704/84432346-5d7def80-ac35-11ea-8828-cb53845a9702.png) ![pic2](https://user-images.githubusercontent.com/47793704/84432350-5f47b300-ac35-11ea-8012-9e82c2c116f7.png)

**Comment by Monokai** [comment]
fixed in 1.1.18
