### ISSUE TITLE
Light version 

### ISSUE THREAD

**Issue by sschuhmann** [Monokai/monokai-pro-vscode#205]
I switch my editor theme according to daytime to have a better readability of my code. I prefer a light theme variant over the day and a darker in the evening. 

Is there any possibility, that there will be a 'light' variant in Monokai Pro matching the other themes?

**Comment by viktor-yakubiv** [comment]
#9 is more old issue related to this

**Comment by vbasky** [comment]
Is this project abandoned ?

**Comment by Monokai** [comment]
Monokai Pro 2.0 has a light version now
