### ISSUE TITLE
Bad color for PHP classes

### ISSUE THREAD

**Issue by scrlkx** [Monokai/monokai-pro-vscode#209]
I am suffering with the choice of colors that identifies the PHP classes in Visual Studio Code.

An example is shown below. As you can see the blue used for the keyword `class` is the same color used for the class name `HomeController`. Maybe we can have a better color combination, something with more emphasis.

![image](https://user-images.githubusercontent.com/22862212/89720415-38dd9400-d9a8-11ea-97ed-e85d93a9b72b.png)

Please let me know if you need any extra information. 
Thanks for your work with Monokai Pro.

**Comment by Ok9xNirab** [comment]
same issu for me !!
