### ISSUE TITLE
1.1.17 Has No Underline on Active Pinned Tabs

### ISSUE THREAD

**Issue by TheV360** [Monokai/monokai-pro-vscode#213]
I'm running VS Code version 1.48.2, and I noticed that pinned tabs don't have an underline when they're selected.

Here's a screenshot showing the problem:

![image](https://user-images.githubusercontent.com/25177071/92206188-29d9ec80-ee55-11ea-9071-cc0229ae884c.png)

**Comment by Monokai** [comment]
Can't replicate in latest VSCode. Maybe VSCode made an update that fixed this?

**Comment by TheV360** [comment]
They changed the behavior of pinned tabs in the most recent update, so by default they have a pin icon and the same appearance as normal tabs, but if you set the `workbench.editor.pinnedTabSizing` setting to `compact` or `shrink`, the smaller tab will have no underline.

![pinned tab that is current tab, but doesn't have an underline](https://user-images.githubusercontent.com/25177071/99582303-f1f03900-29af-11eb-9dd4-8d95487ad23e.png)

**Comment by Tohsig** [comment]
Reviving this for VS Code `1.63.2`. Normal active tabs have an underline, but they do not if `workbench.editor.pinnedTabSizing` is set to `compact` or `shrink`. With `shrink` the color of the pin icon does at least change when the tab is active.

I haven't looked deeply at custom themes in VS Code, but it seems that there isn't an option for underlining condensed pinned tabs. The only solution seems to be having different background colors for the active tab and inactive tabs. If that's true, then that could be a pretty big visual change. Completely understand if that's a non-starter for this theme.
