### ISSUE TITLE
Vue: Wrong color when a HTML tag begins with a capital letter

### ISSUE THREAD

**Issue by bonavida** [Monokai/monokai-pro-vscode#215]
It's been a few days since I noticed that all HTML tags that begin with a capital letter (i.e. custom components) are not well-colored.

This only happens inside a Vue template.

<img width="598" alt="Captura de pantalla 2020-09-11 a las 10 23 50" src="https://user-images.githubusercontent.com/8061481/92893392-eb769b80-f419-11ea-8b1f-9275cf0faa12.png">

Please, can you take a look?
Thanks!

**Comment by Monokai** [comment]
This is an interesting one. Some people want a different color for custom components and others want them to be the same as html elements. Both are valid choices I think. I made a choice after I got some feedback that people wanted them to be different. So, different it is (for now).

**Comment by bonavida** [comment]
> This is an interesting one. Some people want a different color for custom components and others want them to be the same as html elements. Both are valid choices I think. I made a choice after I got some feedback that people wanted them to be different. So, different it is (for now).

@Monokai I see, thank you for the reply.

IMO, it's kinda confusing to see that the custom HTML tag has the same color as the attributes. I think it's harder to read.

I'll take a look into the theme source code and try to change it. Any help would be great, though 😛 (I hope you don't find this offensive, after all I already paid for the Monokai Pro license)

**Comment by Monokai** [comment]
@bonavida Actually, I see now that I'm mistaken. I've actually decided back then to make them all the same color, like you want. This is already the case in React (Sublime and VSCode). And in Sublime, Vue components also have the same color as html elements. Only custom Vue components in VSCode are off. I will update this to be consistent.

**Comment by bonavida** [comment]
Heeya! For the sake of consistancy!

@Monokai Thanks again for taking a look at it.

**Comment by Monokai** [comment]
fixed in 1.1.18
