### ISSUE TITLE
Icons for Crystal files

### ISSUE THREAD

**Issue by pyrsmk** [Monokai/monokai-pro-vscode#216]
I would love to have [Crystal](https://crystal-lang.org) `.cr` files with icons in the file tree. Their logo is available, for example, here : 
https://freebiesupply.com/logos/crystal-logo/

[Crystal](https://github.com/crystal-lang/crystal) is a compiled language with a Ruby-ish syntax. Their repository has 15k stars.

**Comment by Monokai** [comment]
added in 1.1.18
