### ISSUE TITLE
License

### ISSUE THREAD

**Issue by MetaStazz** [Monokai/monokai-pro-vscode#218]
WHAT A JOKE !!!!!!!!!!
"To remove the popups, a license of €9.95 is required" hahaha
**Shame on you....**

**Comment by max-scopp** [comment]
a) Be quiet and accept it that other people put effort into refining things and not being cheap
b) Just press cancel
c) Reverse engineer it and remove the popup
d) Don't be stupid

PS: I'm about to buy it after 2 years using it for free, because I think it's finally worth it

**Comment by MetaStazz** [comment]
lol whatever buddy... I just delete the App.js and it free !!
Fucking capitalist to sell a color theme swap.. Shame on you !!

**Comment by max-scopp** [comment]
Time used for free: 2 years
Expected time to be used: at least 3 more years

10 / (5 * 12) = 0.1666
0.1666 / 30 = 0.005€/day

It just sounds like you're broke af soy boy :D


I removed plenty of license validation checks during my apprenticeship, without whining about it.

**Comment by MetaStazz** [comment]
lol again..... I'm far from broke and for apprenticeship,
It's not about price (even if 10€ is way too expensive for the work), 
**I have Principles !!**
And you have to be a special kind of idiot to pay for this...
You removed plenty of license.. without whining about it.... Nice, good for you...
Oh and I do not cry, it's more a diatribe, against poor people who need to sell expensive license for a bunch of code that a no value !! If you need that to live, well, not sorry to say that you missed something important about programming !!

**Comment by max-scopp** [comment]
You edit quite a lot of your messages, are your thumbs too fat and greasy from eating cheerios and watching anime?

Anyways, I don't think an CEO of a company and well known Designer from a wonderful place where you get the best kush is "poor". Besides, we never forced anybody to buy it, we only said "If this popup annoys you, get a license".

Additionally, there exists jobs out there that are paid to choose colors, think about that.
You're making a theatrical act for nothing from a skewed world view and not even doing your homework.

**Comment by MetaStazz** [comment]
Lol you are still here !! hahaha what a pain... 
And By the way, Hazenberg is not a "well known Designer from a wonderful place where you get the best kush" !! hahaha the joke !!
You're making a theatrical act for nothing from a skewed world view and not even doing your homework. Just go write some shitty code to sell expensive to some looser like you !!

**Comment by max-scopp** [comment]
I don't want that you feel so lonely. :) I'm having a blast on my end.
Got to post this on devRant, this joy must be shared!

**Comment by max-scopp** [comment]
Btw, did you know there is a double exclamation mark? I'm talking about U+203C
I'll get some lunch and be right back, hang tight‼

**Comment by CDuPlooy** [comment]
Came here looking for how to get back a license key if I lost it and found this toxic garbage. For anyone else looking you send an email to `hello [at] monokai.pro` with your paypal purchase details. 

As my SO is a designer I wanted to encourage people like the author to continue putting their work out there. I bought a second license just because you shouldn't have to put up with this.

**Comment by LostInCode404** [comment]
I logged in here just to tell @MetaStazz how shitty he is.

1. It is the wish of the designer to give it for free or not. Also, like @max-scopp said, pay close attention to "If this popup annoys you, get a license". Nobody is forcing you to buy anything.
2. You seem to think it is some kid's job to get some good fancy colors? I'll tell you, it is not. Do you think it is too much to pay for some colors? Look at how almost every online game earns money, by selling cosmetics, mostly (depends game to game) just fancy colors.
3. I still have not bought it, it is a little expensive for me, but I don't cry on github about it. Learn to grow up, you seem like a kid.

This is the *only one* VS Code theme I liked after trying too many of them.

**Comment by Monokai** [comment]
Thanks for your support @max-scopp, @CDuPlooy and @LostInCode404, let's just close this.
