### ISSUE TITLE
Sintax Color Problem

### ISSUE THREAD

**Issue by COD3BREAK3R** [Monokai/monokai-pro-vscode#219]
![Captura de pantalla (73)](https://user-images.githubusercontent.com/51484063/95803787-f9486680-0cce-11eb-90cb-8f7c001201bb.png)
![Captura de pantalla (74)](https://user-images.githubusercontent.com/51484063/95803792-fcdbed80-0cce-11eb-98a8-31c2951872b2.png)
![Captura de pantalla (75)](https://user-images.githubusercontent.com/51484063/95803798-01080b00-0ccf-11eb-99a9-e2fbc42f5842.png)

Occurs in monkai pro syntax and variants, curiously not in the original monokai color scheme, in other themes that error does not occur. Look the screenshots.

**Comment by COD3BREAK3R** [comment]
> Occurs in monkai pro syntax and variants, curiously not in the original monokai color scheme, in other themes that error does not occur. Look the screenshots.

The cause of the problem is here:

![code](https://user-images.githubusercontent.com/51484063/95807549-73c9b400-0cd8-11eb-940a-4b64861ba6f3.png)

I change the color and is ok, but need be fixed in the theme.

**Comment by Monokai** [comment]
Fixed in 1.1.18
