### ISSUE TITLE
jsdoc annotation highlight

### ISSUE THREAD

**Issue by nico29** [Monokai/monokai-pro-vscode#22]
Not a big deal, but it would be nice to have jsdoc annotations (such as `@return`, `@param` ...) highlighted. It would make the information easier to glance.

Thank you 🍪

**Comment by Monokai** [comment]
I added slightly lit up keyword for these things in 1.1.1. I'd like comment blocks as a whole to be recognizable as comments, so that's the reason.

**Comment by bsvipas** [comment]
@Monokai After update `@param/@return/@returns` right now have highlighted type annotations. Thanks!

**Comment by ntwb** [comment]
![screen shot 2017-09-22 at 5 37 54 pm](https://user-images.githubusercontent.com/1016458/30734040-e491eab8-9fbc-11e7-87cb-33073e66ce8b.png)

(Code top, ST bottom)

Any chance on bring those JSDoc highlights over to Sublime Text @Monokai ?

**Comment by Monokai** [comment]
It seems the language definitions for JS I could find (standard / Javascript Next / Javascript Babel) don't support those tags, so I cannot style those in Sublime Text unfortunately.

The JSDoc language is also not completely supported in VSCode as you can see. It doesn't recognize @memberOf, and therefore it doesn't style 'wp' in your screenshot above.
