### ISSUE TITLE
License not found

### ISSUE THREAD

**Issue by ZenekeZene** [Monokai/monokai-pro-vscode#220]
Hi!
Before all, sorry for open an issue for this question, but I don't find a best way to communicate with you.
I've lost the license and I've removed the email (I was bought it a long time ago) with the license.
Could I recover my license or I've to pay again?

Thanks for your time and congrats for these awesome themes 🚀.

**Comment by vagelisp** [comment]
Hello @ZenekeZene, here's how you can restore your license
https://github.com/Monokai/monokai-pro-vscode/issues/218#issuecomment-706056690

**Comment by ZenekeZene** [comment]
Thank you!
