### ISSUE TITLE
React - Different color for Components

### ISSUE THREAD

**Issue by danJecu** [Monokai/monokai-pro-vscode#221]
It will be really nice to have the option to enable a different color to React Components when mixing with HTML tags.

**Comment by BrettBedarf** [comment]
@danJecu 

You can set it explicitly for each theme in settings.json using TextMate scopes. 

Try running **Developer: Inspect Editor Tokens and Scopes** in the Command Palette to see what syntax tokens are being triggered so you know what to set manually 🙂

![Screen Shot 2020-10-23 at 8 49 22 PM](https://user-images.githubusercontent.com/25183985/97066270-4d760500-1571-11eb-8e11-767d3791bcda.png)


This sets each sub theme's components to the same color as Class, which many other themes seem to use as well:

```
"editor.tokenColorCustomizations": {
		
		"[Monokai Pro]": {
			"textMateRules": [
				{
					"scope": [
						"support.class.component.open.jsx", // JSX Component
						"support.class.component.close.jsx"
					],
					"settings": {
						"foreground": "#78DCE8",
						"fontStyle": ""
					}
				}
			]
		},
		"[Monokai Pro (Filter Machine)]": {
			"textMateRules": [
				{
					"scope": [
						"support.class.component.open.jsx", // JSX Component
						"support.class.component.close.jsx"
					],
					"settings": {
						"foreground": "#7CD5F1",
						"fontStyle": ""
					}
				}
			]
		},
		"[Monokai Pro (Filter Octagon)]": {
			"textMateRules": [
				{
					"scope": [
						"support.class.component.open.jsx", // JSX Component
						"support.class.component.close.jsx"
					],
					"settings": {
						"foreground": "#9CD1BB",
						"fontStyle": ""
					}
				}
			]
		},
		"[Monokai Pro (Filter Ristretto)]": {
			"textMateRules": [
				{
					"scope": [
						"support.class.component.open.jsx", // JSX Component
						"support.class.component.close.jsx"
					],
					"settings": {
						"foreground": "#85DACC",
						"fontStyle": ""
					}
				}
			]
		},
		"[Monokai Pro (Filter Spectrum)]": {
			"textMateRules": [
				{
					"scope": [
						"support.class.component.open.jsx", // JSX Component
						"support.class.component.close.jsx"
					],
					"settings": {
						"foreground": "#5AD4E6",
						"fontStyle": ""
					}
				}
			]
		}
	}

```



And [docs for reference](https://code.visualstudio.com/docs/getstarted/themes#_customizing-a-color-theme)

**Comment by danJecu** [comment]
I tried this but it doesn't work..

**Comment by BrettBedarf** [comment]
Hm would you please post a screenshot hovering over a component with the token inspector on like mine as well as the full editor.tokenColorCustomizations section of your settings.com?

**Comment by danJecu** [comment]
![image](https://user-images.githubusercontent.com/60711891/97093191-36571600-164a-11eb-8e19-6bfeff4e966f.png)

"editor.tokenColorCustomizations": {
    "[Monokai Pro (Filter Spectrum)]": {
      "textMateRules": [
        {
          "scope": [" support.class.component.js "],
          "settings": {
            "foreground": "#f5f5f5",
            "fontStyle": "bold"
          }
        }
      ]
    }
  }

**Comment by BrettBedarf** [comment]
Okay, I see what's going on now. I had the [Babel Javascript](https://marketplace.visualstudio.com/items?itemName=mgmcdermott.vscode-language-babel) extension enabled which gives more explicit syntax scopes for new js features/frameworks (varying support by theme)

Anyways, assuming you'd like to keep default syntax highlighting, it looks like Monokai Pro does [intentionally?] set entity tags that are components to the same color as normal elements 🤔

Texmates works like CSS with specificity to prioritize, so MP's "entity.name.tag support.class.component" beats your "support.class.component". 

So just change yours to:
```
"scope": [
		    "entity.name.tag support.class.component"
		]
```

and it should work. I don't think the js & jsx extensions will matter in this context, which means you shouldn't have to do different scopes for .js and .js.jsx for both file types.

**Comment by danJecu** [comment]
![image](https://user-images.githubusercontent.com/60711891/97102803-c7f57080-16a8-11eb-83d2-0fdcf3a649a1.png)
I did exactly what you said and now I'm getting this.
