### ISSUE TITLE
Didn't get invoice

### ISSUE THREAD

**Issue by fanantoxa** [Monokai/monokai-pro-vscode#222]
I did order https://monokai.pro/ some time ago (at Oct 16)
But I didn't get invoice.
At https://monokai.pro/terms it mentioned that 
> We use Quaderno (privacy policy) to send invoices for business purchases
I did write a letter to `support@monokai.pro` and `hello@monokai.nl` but don't see any response yet.

Could you please check mail boxes. I really need that invoice.

**Comment by adrianduncan** [comment]
I have the same issue. I paid for Monokai but all I got was a receipt from paypal?

**Comment by fanantoxa** [comment]
After some time (About a week) I got a response.

**Comment by Monokai** [comment]
please send an email to hello at monokai.pro so we can resolve this
