### ISSUE TITLE
License:

### ISSUE THREAD

**Issue by jparram** [Monokai/monokai-pro-vscode#223]
Not sure if you keep up with licenses, I switched machines and do not have access to the previous license.

**Comment by tststs** [comment]
@jparram any answer? do you by any change remember where to put the licence key. i switched machines to, found the key but have no instructions.

**Comment by jparram** [comment]
Hi,
No answer yet, but with vs code it looks like you can do the ctrl-shift-p,
search for monokai and it will come up with this:

[image: image.png]

**Comment by Monokai** [comment]
To request your license again can you please mail me at hello [at] monokai.pro?
