### ISSUE TITLE
Comments color having low contrast

### ISSUE THREAD

**Issue by AnsonH** [Monokai/monokai-pro-vscode#224]
I think that the color of comments has very low contrast. They are often difficult to read, especially when my monitor's brightness is low. The color of comments (#727072) is kind of similar to the background of the editor:

![Comments demonstration](https://user-images.githubusercontent.com/57580593/97775094-c04a3600-1b98-11eb-8315-704a11837680.png)
 
When I inspect editor tokens in VS Code by running `Developer: Inspect Editor Tokens and Scopes` in the Command Palette (`Ctrl + Shift + P`), the contrast ratio of comments is only 2.89, which is low when we consider that [W3C Standards](https://www.w3.org/TR/2008/REC-WCAG20-20081211/#visual-audio-contrast-contrast) suggests text should have contrast ratios of **at least 4.5** for good accessibility.

<img src="https://user-images.githubusercontent.com/57580593/97775139-3fd80500-1b99-11eb-9767-7ef46f3e2582.png" width="548" height="327">

I'm not sure whether comments are intentionally designed to have low contrast. However, I rely a lot on comments when I code and the low contrast color is making my life difficult. I'm a huge fan of this theme and I wish this issue can be solved.

**Comment by Monokai** [comment]
It's intentionally designed this way, so you can quickly browse through your code and visually "discard" the comments. I understand that some conditions (surrounding light / monitor settings) warrant higher contrast, but in my experience, adjusting the monitor brightness quickly solves it. If you like a bit more clarity, filter "Spectrum" has the highest contrast.

**Comment by AnsonH** [comment]
Thanks for the reply :)
Let me close this issue since it's intentional design
