### ISSUE TITLE
Change comment style from 'Italic' to 'Normal'

### ISSUE THREAD

**Issue by keyrox** [Monokai/monokai-pro-vscode#228]
Is it possible to configure the comments on typescript to 'Normal' instead of 'Italic'?

**Comment by Monokai** [comment]
Monokai Pro styles comments in italic, no user option to make it normal. If you use a font that doesn't have italics, I think it should display all in regular.

**Comment by Ghoul2077** [comment]
I was also looking to change comment style and ended up with this setting.
Place this snippet in settings.json to override monokai pro's settings
```
"editor.tokenColorCustomizations": {
    "textMateRules": [
      {
        "scope": [
          "comment",
          "comment.block",
          "comment.block.documentation",
          "comment.line",
        ],
        "settings": {
          "fontStyle": ""
        }
      }
    ]
  }
```
