### ISSUE TITLE
Extended use bug?

### ISSUE THREAD

**Issue by MaxKyan** [Monokai/monokai-pro-vscode#230]
Got the full license but every time I open VS Code it asks me to purchase a license :/

**Comment by Monokai** [comment]
@MaxKyan Have you entered the license as per the instructions of the license email?

**Comment by MaxKyan** [comment]
Yeah I've entered it as the email instructs

**Comment by Monokai** [comment]
Can you enter your license again please via the command palette: "Monokai Pro: enter license", type 'reset' and then repeat the license instructions?
