### ISSUE TITLE
Double Directory Arrows with other Extensions

### ISSUE THREAD

**Issue by andyboltondev** [Monokai/monokai-pro-vscode#238]
Hi,

I am getting an annoying issue where I am shown 2 arrows alongside directories from other extension file explorers.

This is how it shows in the standard explorer and how I expect it to show in other areas.
![image](https://user-images.githubusercontent.com/32330084/103364250-2d088080-4ab5-11eb-9a91-dfad0ced8084.png)

This is how it is shown in the popular Todo Tree extension (https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree)
![image](https://user-images.githubusercontent.com/32330084/103364300-54f7e400-4ab5-11eb-8286-c2b74f1573c3.png)

Like above this is how it is shown in the SFTP extension (https://marketplace.visualstudio.com/items?itemName=liximomo.sftp)
![image](https://user-images.githubusercontent.com/32330084/103364374-87094600-4ab5-11eb-81c7-4975339c170c.png)

I have confirmed the issue seems to be with this theme. When using a different theme (or icon theme) the issue seems to be resolved. Is there any way to resolve this in your theme with your icon set?

Kind regards,
Andy

**Comment by Monokai** [comment]
Can't replicate this with Todo tree. Did VSCode perhaps fix this in the meantime?

**Comment by andyboltondev** [comment]
Seems to be resolved in the Todo Tree extension now.
![image](https://user-images.githubusercontent.com/32330084/113682863-7f140000-96bb-11eb-9a4f-3c506deae3f2.png)
 
However, issue still seems to be present in the SFTP extension:
![image](https://user-images.githubusercontent.com/32330084/113682956-97841a80-96bb-11eb-8d73-3db5f2489c20.png)

Not sure if this was a VSCode fix, or possibly an update to the extension.
