### ISSUE TITLE
No border is given to inactive input fields

### ISSUE THREAD

**Issue by ajitid** [Monokai/monokai-pro-vscode#24]
![screenshot from 2017-09-16 00-08-10](https://user-images.githubusercontent.com/26769888/30498216-7e2284c0-9a73-11e7-94a7-23297622fb83.png)

Both find and replace have no border because both are inactive. Instead of giving border to input fields, changing background color of that find popup can help.

**Comment by Monokai** [comment]
I think this is solved in 1.1.1

**Comment by ajitid** [comment]
This isn't solved in 1.1.1. The border is still given to active input field.

**Comment by Monokai** [comment]
I think I misunderstood. Let me retry: So when you hit ctrl-f the find/replace box appears. When you then click out of that box, both find and replace are inactive. You want to show that that box is inactive by setting a different background color to that entire box.

While that could make sense, there are no options in the VSCode theme docs to actually do something like that.

**Comment by ajitid** [comment]
Doing he

**Comment by ajitid** [comment]
Using sidebar color for widget background can help.

`"editorWidget.background": "#1e1f2b"` for Octagon theme gives:
![screenshot from 2017-09-29 02-12-37](https://user-images.githubusercontent.com/26769888/30989632-f7647008-a4bb-11e7-82af-c76513b99936.png)
