### ISSUE TITLE
I bought Monokai Pro. The pop up telling me my free-trial is over pops up relentlessly. 

### ISSUE THREAD

**Issue by TABLEWORX** [Monokai/monokai-pro-vscode#240]
How do I make it stop?

**Comment by Monokai** [comment]
Are you sure you've filled in your details correctly according to the license instructions? A license should prevent the popups completely.

**Comment by gmaphane** [comment]
Same here. Bought a license but I haven't received an activation key/license instructions. I emailed the developer but no response

**Comment by Monokai** [comment]
I'm using SendGrid to automatically send license emails, but sometimes an email gets caught by an overzealous spam filter..

If you bought a license and didn't receive an email, something went wrong. Please email at `hello at monokai.pro` so I can send your license manually.

@gmaphane I'm not sure I've received your email. I don't see any outstanding emails in my inbox.

**Comment by gmaphane** [comment]
Hi

I received the license. Thank you so much

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rtilliman** [comment]
Hello, I sent an email to hello at monokai.pro and I still have not received an activation email with credentials. I have proof of purchase and no way to activate it. Please help.
