### ISSUE TITLE
I bought a monokai pro license for vscode, but by mistake I lost it

### ISSUE THREAD

**Issue by Agustin29** [Monokai/monokai-pro-vscode#242]
I bought a monokai pro license for vscode, but by mistake I lost it, it was not possible to verify that what I said is true and to be able to send me the license again, thanks.

**Comment by Monokai** [comment]
Hi, can you please email me your email address / transaction ID to hello at monokai.pro so we can settle this? Thanks.

**Comment by Agustin29** [comment]
agustinbatista92@gmail.com

2TP8445229665711P
