### ISSUE TITLE
Java Imports

### ISSUE THREAD

**Issue by regadas** [Monokai/monokai-pro-vscode#243]
Hello! really love this! Great job! 👏 

I wonder if it's possible to improve a little bit java imports. Currently they look like

![java](https://user-images.githubusercontent.com/163899/109419960-f0c7a280-79c7-11eb-9937-a5f998aa47fd.png)

and I think it would be great if they could look similar to what we see in scala

![scala](https://user-images.githubusercontent.com/163899/109420015-28cee580-79c8-11eb-90b4-bebe24631f4d.png)

Thanks!

**Comment by Monokai** [comment]
I'd very like to, but themes depend on syntax definitions and it seems the Java syntax definition doesn't differentiate between those different parts of the code. You can check by yourself by clicking on "Inspect editor tokens and scopes" from the command palette and move the cursor around.
