### ISSUE TITLE
Email No reply

### ISSUE THREAD

**Issue by QueM775** [Monokai/monokai-pro-vscode#245]
I purchased Monokai -pro for vscode. I had to reinstall VSCode and now Monokai-pro wants me to enter my license. I can't find the email so I went to the site and I have sent a couple of emails asking for help. below is proof I bought it.
![monokai](https://user-images.githubusercontent.com/53785583/112055036-b9fb2d00-8b2c-11eb-9a49-27e8f1e499b5.jpg)

Email address equade@gmail.com

**Comment by Monokai** [comment]
Checking in here as well. I've sent you an email on the 10th of March, and again just now. If you haven't received anything, could you please let me know?
