### ISSUE TITLE
open file and changed file have same color

### ISSUE THREAD

**Issue by JoeCianflone** [Monokai/monokai-pro-vscode#249]
![Screen Shot 2021-04-21 at 12 01 30 PM](https://user-images.githubusercontent.com/989648/115585477-a3fe9a80-a299-11eb-897c-6d180bb92cb3.png)

Attached is my VSCode project window. The file `casks.sh` has been edited and not yet updated in git. The `editorsettings.sh` file is *open* but has not been edited. 

It's the same with the tabs, but at least there I've got a little `M`

![Screen Shot 2021-04-21 at 12 06 29 PM](https://user-images.githubusercontent.com/989648/115585890-06579b00-a29a-11eb-81e2-9456e4949191.png)

Ideally, the "open but not yet changed" should be a different color to give a better visual indication of where you are and what has happened in that file.

**Comment by JoeCianflone** [comment]
I ended up adjusting 
```json
    "[Monokai Pro (Filter Octagon)]": {
      "gitDecoration.modifiedResourceForeground": "#f8f4ea",
    }
```
which looks nice on this theme

**Comment by Monokai** [comment]
I have a minimal set of colors, so I can only do so much differentiation. Personally I like my editor to be a little bit more understated and have disabled `workbench > editor > decorations > colors` and `explorer > decorations > colors`. That way you can differentiate the active file, and still see the modified git status.
