### ISSUE TITLE
Monokai for Python doesn't look as good in VS Code as eg Sublime Text

### ISSUE THREAD

**Issue by anentropic** [Monokai/monokai-pro-vscode#252]
I'm enjoying the Monokai Pro theme in VS Code for other languages

But for Python it looks worse in VS Code than in Sublime Text

Specifically:
- in VS Code docstrings are rendered as bright "string yellow" instead of subdued "comment grey"... this is the one that makes me want to not use it
- in VS Code class names are "generic turquoise" instead of "class or function green"

VS Code:
![Screenshot 2021-05-11 at 16 06 44](https://user-images.githubusercontent.com/147840/117839781-72af3400-b273-11eb-8f76-50865361dc84.png)

Also, in ST3 the `@dataclass` decorator is generic turquoise the same as the `@classmethod` one, whereas in VS Code they are different (see screenshot above). I'm not sure which is more correct, but maybe decorators should all be "function green"?

**Comment by Monokai** [comment]
I've changed the docstrings in 1.1.20
