### ISSUE TITLE
The lock icon for the Live Share extension 

### ISSUE THREAD

**Issue by SiarheiBobryk** [Monokai/monokai-pro-vscode#253]
Dear @Monokai!

Recently I've installed the following Microsoft extensions: [Live Share](https://marketplace.visualstudio.com/items?itemName=ms-vsliveshare.vsliveshare) and [Live Share Audio](https://marketplace.visualstudio.com/items?itemName=ms-vsliveshare.vsliveshare-audio).

After that, I got the lock icon at the bottom of VSCode which does not match Monokai Pro styling.

<img width="1792" alt="Screen Shot 2021-05-16 at 1 26 14 pm" src="https://user-images.githubusercontent.com/33809585/118394075-313fcf80-b64b-11eb-8902-16b56cc7f608.png">

Are you planning to add support to Live Share in the future?

**Comment by Monokai** [comment]
Think this should be fixed by this plugin?
