### ISSUE TITLE
Lost my license

### ISSUE THREAD

**Issue by finalwhy** [Monokai/monokai-pro-vscode#254]
I accidentally lost the email containing my license. Can you resend me a copy? 
please give me an email so I can send you the information I filled in at the time of my purchase  to help you identify my order
thanks

**Comment by brouk2426** [comment]
How did you solve this issue??

**Comment by finalwhy** [comment]
> How did you solve this issue??

I retrieved my license from my email ... : )

**Comment by finalwhy** [comment]
> Thanks.. but I lost my license email... 😭

[Email](hello@monokai.pro)，maybe you can contact them through this email address

**Comment by brouk2426** [comment]
> Email，maybe you can contact them through this email address

Thanks !!  : )
