### ISSUE TITLE
Coloring '*' incorrectly in C/C++

### ISSUE THREAD

**Issue by YXuewei** [Monokai/monokai-pro-vscode#257]
In C and C++ files, monokai pro coloring * as blow 
![无标题](https://user-images.githubusercontent.com/13243206/122210034-c1d22f80-ced7-11eb-81ed-0e6669c2519c.png)
However, * of fptr should be red, and last reverse bracket should be normal but red.

**Comment by Monokai** [comment]
I can't replicate this. Maybe VSCode updated their syntax definitions in the meantime.
