### ISSUE TITLE
Paid for a license, still get a pop-up

### ISSUE THREAD

**Issue by yochishor** [Monokai/monokai-pro-vscode#258]
I paid for a license a while ago and still got the pop-up every time I used vsCode

**Comment by charlestbell** [comment]
Same

**Comment by akiraah** [comment]
Me too, why hasn't there been an official response?

**Comment by akiraah** [comment]
They still haven't updated, no responded to any ongoing issues. I'll be issuing a charge back, not paying for crappy service.

**Comment by EvilPolygon** [comment]
i found solution:

1) find folder with extensions 
   ~/.vscode/extensions/monokai.theme-monokai-pro-vscode<version> for linux
   %USERPROFILE%\.vscode\extensions for windows
2) find folder with monokai
3) then js/app.js
4) set this.thankYouMessageShown = true
5) restart vs code

**Comment by akiraah** [comment]
> 



> i found solution:
> 
> 1. find folder with extensions
>    ~/.vscode/extensions/monokai.theme-monokai-pro-vscode for linux
>    %USERPROFILE%.vscode\extensions for windows
> 2. find folder with monokai
> 3. then js/app.js
> 4. set this.thankYouMessageShown = true
> 5. restart vs code

I found this folder monokai.theme-monokai-pro-vscode-1.1.19 but couldn't find the boolean you've mentioned.

**Comment by Monokai** [comment]
Please email to hello@monokai.pro for all licensing questions.
