### ISSUE TITLE
Update regexp

### ISSUE THREAD

**Issue by ajitid** [Monokai/monokai-pro-vscode#26]
https://code.visualstudio.com/updates/v1_17#_improved-colorization-in-dark-and-light-themes

**Comment by Monokai** [comment]
Monokai Pro already does some regex highlighting. Do you have suggestions to improve it?

**Comment by ajitid** [comment]
In 1.17, VS Code has introduced more keys to highlight regex. For example, there is a key for square brackets as a regex instead of falling back as a punctuation.

Monokai Pro:
![screenshot from 2017-10-14 15-53-50](https://user-images.githubusercontent.com/26769888/31574943-956a38c6-b0f8-11e7-9e01-5aa187620066.png)

Dark+:
![vg](https://user-images.githubusercontent.com/26769888/31574945-9ee8a126-b0f8-11e7-9204-cdfe8ecd3e3a.png)
