### ISSUE TITLE
Add support for codespaces

### ISSUE THREAD

**Issue by plttn** [Monokai/monokai-pro-vscode#263]
![image](https://user-images.githubusercontent.com/7369280/129076171-881b192b-ec3e-40c7-be0f-17f333403f4b.png)

https://code.visualstudio.com/docs/remote/codespaces#_why-is-an-extension-not-installable-in-the-browser

**Comment by ntwb** [comment]
I just learnt about github.dev

https://twitter.com/code/status/1425503238145650691

https://twitter.com/github/status/1425505817827151872

Screenshot below is me opening this repo, alas Monokai Pro doesn't work

I highly guess it's the same reasons for github.dev as codespaces above....
<img width="1364" alt="image" src="https://user-images.githubusercontent.com/1016458/130226410-87e2d5e7-b9ab-4175-842f-954e64484222.png">


Now to work out how to get Operator Mono running there in the mean time...

**Comment by joshuabeny1999** [comment]
Yes i am missing this feature too.

**Comment by Monokai** [comment]
Web extension compatibility has been added in 1.2.0.
