### ISSUE TITLE
Enabling Monokai Pro in Restricted Mode

### ISSUE THREAD

**Issue by BasixKOR** [Monokai/monokai-pro-vscode#264]
VS Code introduced [restricted mode](https://aka.ms/vscode-workspace-trust) to disable certain features while working on untrusted codebase. However Monokai Pro is disabled even though it is merely a theme.

**Comment by soimon** [comment]
In the meantime you can add this snippet to your `settings.json` to force the extension to function in restricted mode.
```
"extensions.supportUntrustedWorkspaces": {
    "monokai.theme-monokai-pro-vscode": {
        "supported": true
    }
}
```
Could be a tricky move, but I'm also assuming the extension is merely a theme and does not execute any workspace code.

**Comment by Monokai** [comment]
I've added this per the instructions of VSCode to package.json in 1.1.20. Should be fixed now.
