### ISSUE TITLE
bracket pair colorization doesn't use Theme colors

### ISSUE THREAD

**Issue by fanantoxa** [Monokai/monokai-pro-vscode#269]
VSCode has just released 
[High performance bracket pair colorization](https://code.visualstudio.com/updates/v1_60#_high-performance-bracket-pair-colorization)
That allow to have brackets pair to have different colors to better understand pairs.
![bracket-pair-colorization-on-off drawio](https://user-images.githubusercontent.com/7717033/132245568-0182667d-7b94-4805-b027-85054f00d49a.png)

Issue: It doesn't use theme colors so all brackets looks a bit different from code.
Here some examples:
![sssss](https://user-images.githubusercontent.com/7717033/132245794-b3fe1d0e-39d9-41a0-96ea-8f9ee745ca3b.jpg)

Proposal:
Since bracket pair colorization now is built in into VSCode, update theme to set colors for brackets.

Thanks, Anton :slightly_smiling_face:

**Comment by outaTiME** [comment]
Here is an example of how to achieve this

![image](https://user-images.githubusercontent.com/140472/132674382-4fe2db45-f925-449c-b8e6-f6c479d28ea4.jpeg)

**Comment by Monokai** [comment]
I've added the theme colors for the bracket matching. Personally I find it a bit too much, but at least it's there now.
