### ISSUE TITLE
No-Italics Option

### ISSUE THREAD

**Issue by svictoreq** [Monokai/monokai-pro-vscode#27]
Current Version: 1.1.2
VSCode Version: 1.17.0

Can you make any No-Italic option for the themes?

**Comment by Monokai** [comment]
This is not a bad idea in itself, but it complicates things a lot. I would either have to create the theme dynamically, or double each theme. If I'd like to include another option, it expands exponentially.

Could you maybe explain why you want this?

**Comment by svictoreq** [comment]
I understand. I actually modified the theme by myself and duplicate the themes individually. I want it because I don't have Operator Mono, I use Fira Code, and I really don't like the looks with italics, but as you said, it may be very complicated...

**Comment by Jcrs** [comment]
Hi there, 

There is already an open PR to add a global option to toggle italics. 
However, as a workaround, you can simply add those configurations to your local settings and it works perfectly!

https://github.com/Microsoft/vscode/issues/32579

**Comment by SNikalaichyk** [comment]
Hi @Monokai,
Unfortunately it has not been addressed in VS Code since this issue was closed. The workaround that is suggested there is hideous. Love the theme, bought the license and realized that I hate italic fonts. Can we have this issue reopened?
A setting like this would be really nice to have:
```json
"monokaiPro.noItalics": true
```

**Comment by jeduan** [comment]
These changes to `settings.json` made it work for me without italics. 

```json
    "editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": [
                    "storage.type",
                    "variable.parameter",
                    "parameters variable.function",
                    "support.type",
                    "storage.modifier",
                    "entity.other.inherited-class",
                    "entity.other.attribute-name"
                ],
                "settings": {
                    "fontStyle": "italic"
                }
            }
        ]
    },
```

**Comment by zeroxia** [comment]
> 

Thanks for this hint. Since I hate italics everywhere, so I added `"comment",` to the array of `"scope"`.

**Comment by ABIRHS** [comment]
Can you please guide me step by step? I dont know how could i remove italice from my monokai pro theme. i dont like italics. I do not understand what u r saying.
