### ISSUE TITLE
Fix  @workspaceUnsupported so Monokai Pro can work in untrusted VS Code workspaces

### ISSUE THREAD

**Issue by simonrolfe** [Monokai/monokai-pro-vscode#270]
VS Code, as of v1.59 (I think) has the notion of workspace trust, where extensions that run code or could do other nefarious things are disabled until you trust the workspace. 

Monokai Pro, being a theme, presumably doesn't do any of this stuff so I imagine there's no reason why it couldn't be updated to [support workspace trust](https://code.visualstudio.com/api/extension-guides/workspace-trust).

If this is done, then I could use Monokai when exploring other codebases, temp files etc. and keep my eyes happy 😊

**Comment by BasixKOR** [comment]
Seems like duplicate of #264?

**Comment by simonrolfe** [comment]
Yes, looks like it - apologies.
