### ISSUE TITLE
[Python] Global variable color

### ISSUE THREAD

**Issue by mrhaa** [Monokai/monokai-pro-vscode#272]
Hi everyone~ and Monokai team.

I'm enjoying the Monokai Pro theme in VS Code for python. and I love it so much.

In python, however,
global variables such as `GLOBAL_PARAMETER = 14`
are not highlighted.

![image](https://user-images.githubusercontent.com/4934671/134868584-ac614778-6a7f-41f2-9f7d-82a92940a5e6.png)

Please make them colored.

Thanks in advance.

**Comment by Monokai** [comment]
fixed in 1.1.20
