### ISSUE TITLE
Update to web extensions (github.dev)

### ISSUE THREAD

**Issue by BasixKOR** [Monokai/monokai-pro-vscode#276]
github.dev and other web-based VS Code environment will only run so-called 'web extensions'. This enables users without VS Code access to use Monokai Pro and quickly glance at the code without cloning everything.

Check [Microsoft guide](https://code.visualstudio.com/api/extension-guides/web-extensions#update-existing-extensions-to-web-extensions) for details.

**Comment by BasixKOR** [comment]
Related: #263

**Comment by igor-kupczynski** [comment]
Yes please!

**Comment by BenJetson** [comment]
I would love to see this working in VScode for web. I frequently use the <kbd>.</kbd> shortcut on the GitHub website to quickly glance at repos in a more familiar environment.

The error message I see for the extension points to a different reference than the one already mentioned, so I wanted to leave this here. This explains some of the limitations of the browser extensions:
https://code.visualstudio.com/docs/editor/vscode-web#_extensions

**Comment by Monokai** [comment]
Web extension compatibility has been added in 1.2.0.
