### ISSUE TITLE
Installation on code-server Container image

### ISSUE THREAD

**Issue by 0Architectus0** [Monokai/monokai-pro-vscode#277]
Not really an issue; more of a question. Is it possible to get/install this extension on the code-server container created by [cdr/code-server ](https://github.com/cdr/code-server)? I paid for the Monokai-Pro theme and I'd like to use it there. 
Cheers!

**Comment by watermarkhu** [comment]
You download the extension on VS code, navigate to the /vscode/extensions folder, and copy the extension to the same folder of the code server. After restarting Code server the theme will show up.

**Comment by Monokai** [comment]
Web extension compatibility has been added in 1.2.0, does this also work in code-server?

**Comment by tomcarman** [comment]
Yep - it now appears available as an Extension on code-server - thanks!
