### ISSUE TITLE
Dart syntax highlighting (coloring)

### ISSUE THREAD

**Issue by pacifi5t** [Monokai/monokai-pro-vscode#279]
1. `[ ]`, `{ }`, `()`, `" "` & `' '` are not colored dim gray as they are in other languages
2. `=>` operator for getters and setters is white (but for arrow functions it's colored properly)

**Comment by Monokai** [comment]
Unfortunately the Dart language syntax definition is quite bare bones. The syntax definition is where it parses all the different tokens so color schemes can target them. For Dart, there are simply not enough tokens to style.
