### ISSUE TITLE
Color-Blind Option?

### ISSUE THREAD

**Issue by nshtg** [Monokai/monokai-pro-vscode#28]
Have you considered adding a color blind option/filter?

**Comment by Monokai** [comment]
That's a good suggestion, but I'm not sure this will work in this color palette. I tried to balance the perceived lightness of the colors of Monokai Pro. And while that looks harmonious to people that can see color, it actually might look as if there's no difference for people who can't.

Of course you have all kinds of variations in color blindness. I will try and test this in the future and see if I can adjust something.
