### ISSUE TITLE
Icon for TypeScript

### ISSUE THREAD

**Issue by erikMagnussonSoftware** [Monokai/monokai-pro-vscode#287]
I don't know how much more I can add.

<img width="118" alt="image" src="https://user-images.githubusercontent.com/33495800/152283504-762cbd07-e37a-424a-802e-52bb9bcaa2b1.png">

Everything else is so nice.

**Comment by Monokai** [comment]
Do you mean you want a different TS icon? This is a pixelized interpretation of the Typescript logo.
