### ISSUE TITLE
C++ static function not colorized properly

### ISSUE THREAD

**Issue by yantaozhao** [Monokai/monokai-pro-vscode#292]
C++ code `static` function not colorized properly.
```cpp
class C {
  public:
    int foo() {}         // `foo` colorized
    static int bar() {}  // `bar` not colorized. Expectation: color as `foo`
};
```

![image](https://user-images.githubusercontent.com/9587405/158740503-4329d8a6-fc20-4a40-abac-c4cee8fce9ed.png)

**Comment by Monokai** [comment]
fixed in 1.1.21
