### ISSUE TITLE
License Email Lost

### ISSUE THREAD

**Issue by brianpham** [Monokai/monokai-pro-vscode#294]
I am trying to recover the license so that I can re-activate the theme again. Can you help with sending the license again? I sent an email to hello@monokai.pro, but haven't heard back yet.

**Comment by N00ree** [comment]
I also lost my license after a pc reset. Help is appreciated. I can also provide the Paypal transaction code.

**Comment by N00ree** [comment]
The dev contacted me, and I got my license back. Thanks!
