### ISSUE TITLE
Please add better FLUTTER/Dart support as well as icons

### ISSUE THREAD

**Issue by fisforfaheem** [Monokai/monokai-pro-vscode#295]
icons in a flutter project so simple so have to use material theme icons....also the theme can add flutter related UI changes

**Comment by fisforfaheem** [comment]
Good Theme, better than all others but: 
 Please support FLUTTER/DART also the icons
for flutter project is so bad cant use its icon theme.

**Comment by fisforfaheem** [comment]
???

**Comment by Monokai** [comment]
Dart icons are there. I'm not familiar with Flutter. What exactly is missing from a Flutter project?

**Comment by fisforfaheem** [comment]
brother add files icons like .yaml file, and folders used I
flutter project... also the code colors don't look good in flutter dart as
compared to HTML etc



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
11/27/22,
02:19:38 PM
