### ISSUE TITLE
Icon for Hare language

### ISSUE THREAD

**Issue by lovelymono** [Monokai/monokai-pro-vscode#296]
Would it be possible to have an icon for the [Hare](https://harelang.org/) programming language? It's mascot is a small, fuzzy bunny, Hariette:

![image](https://user-images.githubusercontent.com/99364286/165381759-cc0c24b9-f177-4e99-8369-ed5bbae2902e.png)

The icon could be a simplified version of the mascot, similar to PHP and OCaml ones, or simply a bnuuy face, which I think would work fine as well.

**Comment by Monokai** [comment]
I added a Hare icon in 1.1.21. The original logo perspective turned out to be a bit too detailed, so I drew a front-faced hare instead.
