### ISSUE TITLE
JavaScript Colors?

### ISSUE THREAD

**Issue by jfilipeferreira96** [Monokai/monokai-pro-vscode#297]
Why did the JS colors changed?

**Comment by picocode1** [comment]
Same issue here.

**Comment by bestwebua** [comment]
The same, changed for a lot of langs. For what these ugly red colors for method args definitions? Uhh, I hate this update at all. Roll back it, please!

<img width="325" alt="Screenshot 2022-05-18 at 13 22 05" src="https://user-images.githubusercontent.com/14002692/169027471-2de49a9f-f4a5-4c76-a878-91802854d7c2.png">

**Comment by bestwebua** [comment]
If the same issue like mine, you can disable new vscode [feature](https://code.visualstudio.com/updates/v1_67#_bracket-pair-colorization-enabled-by-default) that was enabled by default after 1.67 update:

<img width="1233" alt="Screenshot 2022-05-18 at 13 32 56" src="https://user-images.githubusercontent.com/14002692/169029554-012c8482-a315-42e4-bb35-28d599959def.png">

https://github.com/microsoft/vscode/issues/149345#issuecomment-1125870394

**Comment by CatnipMountain** [comment]
> In fact, this isn't an Monokai Pro issue. If you have the same issue like mine, you can disable new vscode [feature](https://code.visualstudio.com/updates/v1_67#_bracket-pair-colorization-enabled-by-default) that was enabled by default after 1.67 update:
> 
> <img alt="Screenshot 2022-05-18 at 13 32 56" width="1233" src="https://user-images.githubusercontent.com/14002692/169029554-012c8482-a315-42e4-bb35-28d599959def.png">
> 
> [microsoft/vscode#149345 (comment)](https://github.com/microsoft/vscode/issues/149345#issuecomment-1125870394)

That's perfect, thank you! It's been driving me mad why the bracket colors changed and were so hard to see
