### ISSUE TITLE
Menu problems: Grayed-out items are indistinguishable from active items

### ISSUE THREAD

**Issue by skycommand** [Monokai/monokai-pro-vscode#298]
Hello. In the 2022-01-19 release of Monokai Pro, it is difficult to tell which menu item is active and which one is not. Here is a sample screenshot.

![Monokai Pro's low contrast problem in the menus](https://user-images.githubusercontent.com/17097175/167515576-e1e0f8df-069f-4fe5-81cb-54dead40675e.png)

Here is an example of how the menu should look. (Warning: The following is a photoshopped mock-up.)
![Mockup - Active menu items vs  inactive ones](https://user-images.githubusercontent.com/17097175/167516125-66811561-3421-49e0-bd14-62b5afe0e22f.png)

**Comment by Monokai** [comment]
@skycommand I've added new theme colors in 1.1.21 and have tested it on the Windows version. It seems to work ok now, can you please confirm?

**Comment by skycommand** [comment]
I confirm.
