### ISSUE TITLE
Feedback on quick pick

### ISSUE THREAD

**Issue by Tyriar** [Monokai/monokai-pro-vscode#3]
ctrl+p file search is showing red.

It's also giving very little contrast between search match and highlighting the active item which makes it difficult to quickly see which file is selected.

<img width="606" alt="screen shot 2017-08-21 at 10 19 06 am" src="https://user-images.githubusercontent.com/2193314/29530800-4d146722-865a-11e7-9c82-40eddcc07c79.png">

**Comment by Monokai** [comment]
fixed in 1.1.0
