### ISSUE TITLE
Paid for monokai pro vs code. Still have not received a license

### ISSUE THREAD

**Issue by uchennodim** [Monokai/monokai-pro-vscode#300]

**Comment by uchennodim** [comment]
Hello, is anyone there?

**Comment by derynL** [comment]
Yes, me too. Refund please - I'm not interested in supporting businesses who can't be bothered to fulfil their end of a simple transaction.

**Comment by Monokai** [comment]
Very rarely an email provider blocks the automatic license email I'm sending upon purchase. I believe @uchennodim received his license by now. @derynL can you please email me at `hello at monokai.pro` so we can sort it out?

**Comment by uchennodim** [comment]
License received.
