### ISSUE TITLE
The color of the terminal remains the same as that of the editor

### ISSUE THREAD

**Issue by shenghui0779** [Monokai/monokai-pro-vscode#303]
![image](https://user-images.githubusercontent.com/67535398/174768734-ab2e4e4c-8565-495a-af24-b2fd64c155ff.png)

**Comment by Monokai** [comment]
Not sure what you mean? The terminal background color is different from the editor.

**Comment by shenghui0779** [comment]
I hope the background color of the terminal is the same as that of the editor.

**Comment by Monokai** [comment]
I see the terminal as a different panel. Ideally I also would want it to have a darker ("normal") background, but in order to differentiate from the main editor, I think this is the best solution for now.
