### ISSUE TITLE
File diff looks confusing with dotted lines

### ISSUE THREAD

**Issue by brunobertoldi** [Monokai/monokai-pro-vscode#31]

**Comment by bsvipas** [comment]
Same for me :)

**Comment by ayrtonmassey** [comment]
Agreed, the default styling (solid colour with no border, brighter area indicates characters changed) is much easier to read. I like your theme but I can't use it for this reason.

**Comment by gecharo** [comment]
+. That dashed lines are very confusing & doesn't help to track differences at all. Solid colors would be way better.

**Comment by Monokai** [comment]
Fixed in 1.1.5
