### ISSUE TITLE
Different colors for React Component names vs. attributes

### ISSUE THREAD

**Issue by rkpatel33** [Monokai/monokai-pro-vscode#32]
Just bought a license, the theme is beautiful.

I wonder if it was intentional to have React component names the same color as attributes on that component as in the screenshot below:

![image](https://user-images.githubusercontent.com/3799489/32636240-c0282e90-c568-11e7-9633-c23e5dfc70a9.png)

I would love to see a different color for the two to make it easier to read, maybe mirroring the plain old HTML syntax coloring.

**Comment by Monokai** [comment]
Fixed in 1.1.5

**Comment by mattietea** [comment]
I'm still having this issue on 1.1.8

**Comment by saulius-spiridonas-ht** [comment]
It is still an issue
