### ISSUE TITLE
Python match case support 

### ISSUE THREAD

**Issue by meghiaws** [Monokai/monokai-pro-vscode#321]
Colorizing doesn't apply to python match case.

![image](https://user-images.githubusercontent.com/57438346/193030608-d9d100a3-4831-46c4-b652-274efe331996.png)

**Comment by Monokai** [comment]
Unfortunately these keywords don't have a scope defined in the Python syntax definitions of VSCode, so themes cannot color them. It's up to VSCode to update its syntax definition.

**Comment by apsyhea** [comment]
> К сожалению, эти ключевые слова не имеют области, определенной в определениях синтаксиса Python VSCode, поэтому темы не могут их окрашивать. VSCode должен обновить определение синтаксиса.
Theme VS Code dark:
![image](https://user-images.githubusercontent.com/37932705/221535892-1deb530f-5760-4405-8613-953218f79fca.png)
Theme Github dark:
![image](https://user-images.githubusercontent.com/37932705/221536295-b2525922-fd28-4b8f-8650-d441e6fedf5c.png)

**Comment by Monokai** [comment]
Turned out I had the MagicPython extension installed, which is already the default Python highlighter in VSCode. They recommend to uninstall the MagicPython extension, which solved the issue in my case.

**Comment by GitWumm** [comment]
I have the same issue as above, but in my case the normal Monokai theme highlights the "match" and "case" keywords, while the Monokai Pro themes don't. And I don't have the MagicPython extension installed, so is there any update on this topic? Or could it be another python extension interfering?
![MonokaiPro](https://github.com/user-attachments/assets/60327aa6-d8be-4f71-9c0f-769b280c4a76)
![Monokai](https://github.com/user-attachments/assets/64afee9a-62be-4f4f-a29e-b421718bc4d6)
