### ISSUE TITLE
Font garbled while writing Korean commit message

### ISSUE THREAD

**Issue by 5kdk** [Monokai/monokai-pro-vscode#324]
![image](https://user-images.githubusercontent.com/86090355/201431217-6a8c35e8-3377-4bb7-b1b3-f1fcc9b9acc5.png)

Other themes don't have this problem.

**Comment by Monokai** [comment]
The Monokai Pro theme doesn't alter fonts like this, so even though other themes don't have this issue, I still think it's an issue with VSCode somehow. Could you please create an issue at the VSCode repository? https://github.com/microsoft/vscode
