### ISSUE TITLE
No coloration for typescript files after purchase

### ISSUE THREAD

**Issue by ThomasH13090** [Monokai/monokai-pro-vscode#326]
Hello, I'm facing a very frustrating issue where coloration of vars, keywords etc is working with html, css files but not with typescript ones. 

I started just a the end of the trial and now that I purchased it it doesn't see to solve the problem. I tried to clean my pc, uninstall vs code, reinstall code and the extensions etc. Nothing seem to work...

Than you for the help....

[
<img width="1432" alt="html" src="https://user-images.githubusercontent.com/26181893/202453851-727751ce-c452-4b3e-a9ba-c0b60fbd05e8.png">
](url)

[
<img width="1432" alt="typescript`" src="https://user-images.githubusercontent.com/26181893/202453924-8993b978-93d2-4de9-89d7-5c8d4d28ae9d.png">
](url)

**Comment by Monokai** [comment]
I cannot replicate this. Does VSCode say that the file has Typescript Syntax?
