### ISSUE TITLE
Purchased a license

### ISSUE THREAD

**Issue by aikiart** [Monokai/monokai-pro-vscode#327]
I just purchased a license but can't figure out how to apply the license in visual code.  I've loaded command palette and selected "Monokai Pro: but don't see a place to enter the license from the email.
![monokai](https://user-images.githubusercontent.com/1198317/204055477-1fd0e6b1-84f2-4e7a-b4a8-a2090cfbadd6.JPG)

**Comment by Monokai** [comment]
You can enter the command palette via `menu > view > command palette`. From there, type `Monokai Pro: enter license` and hit `enter`. It allows you to enter the license information.

**Comment by aikiart** [comment]
Thank you!!!
