### ISSUE TITLE
Multi-line comments non italic font settings (feature request)

### ISSUE THREAD

**Issue by DolphinDream** [Monokai/monokai-pro-vscode#328]
I love this theme (for VSCode) but there is one major thing that stops me from using it more often which is the fact the multi-line comments have italic fonts. Often time I have ascii diagrams displayed in these comment sections and the italic font messes up the diagrams. Is it possible to have the comments NOT italicized or at least an option to turn the italics off for these comment scopes ? 
(see screenshot .. Monokai vs default VSCode dark theme. This simple ascii diagram example is not that bad having italic font, but for some other more complex ascii diagrams italics messes up the diagram enough to make it unreadable). 

![multi-line-comment-monokai-pro](https://user-images.githubusercontent.com/2083719/205129527-be57d19b-0574-4ca5-b638-99f4e2d68318.jpg)

**Comment by Monokai** [comment]
I understand. In this case it's best to add this to `settings.json`:

```
"editor.tokenColorCustomizations": {
    "comments": {
        "fontStyle": "normal"
    }
}
```
