### ISSUE TITLE
Nested Sass

### ISSUE THREAD

**Issue by nickfmc** [Monokai/monokai-pro-vscode#34]
would be nice to have nested Sass styles.  if you have the following I would expect the span to be monokai red not white!

`div {
text-align: center;
span {
text-align:left;
}
}
`

**Comment by Monokai** [comment]
I think this is fixed now. Probably the syntax definitions were updated

**Comment by ajitid** [comment]
@Monokai can you close all fixed issues in this repo? This gives us ease to search for existing issues and avoiding duplication
