### ISSUE TITLE
About telemetry

### ISSUE THREAD

**Issue by DARKBOW923** [Monokai/monokai-pro-vscode#346]
`We track website visits via Google Analytics. We make sure your IP address is anonymized, so there's no personally identifiable information transferred to Google Analytics.`

That means that monokai only tracks the website visits ONLY for monokai.pro, or it will track ALL the website i visit?

Thanks for the help.

**Comment by Monokai** [comment]
I'm only tracking visits to monokai.pro. Like every analytics tracker, it also tracks the referrer page (the previous site that links to monokai.pro).
