### ISSUE TITLE
Template Literal color inconsistent in Js

### ISSUE THREAD

**Issue by DevAlvaroF** [Monokai/monokai-pro-vscode#349]
Hi!

I was working with the following piece of code (image to make the differences visible) and I found that the template literal has different colors inside of a class. This makes it really hard to read when it's all yellow. 

However, if inside an if, the brackets change to green.
![image](https://user-images.githubusercontent.com/87340855/223630229-3067888b-dc1b-4158-9066-198f7959f283.png)

On the other hand, outside of the class method (as a global variable), color changes again
![image](https://user-images.githubusercontent.com/87340855/223630294-29e69d40-200b-4b9d-8bcd-ef4ce2a52162.png)

```
class Workout {
#renderWorkout(workout) {
    let htmlWorkout = `
        <li class="workout workout--${workout.type}" data-id="${workout.id}">
        <h2 class="workout__title">${workout.description}</h2>
        <div class="workout__details">
        <span class="workout__icon">${workout.emoji}</span>
        <span class="workout__value">${workout.distance}</span>
        <span class="workout__unit">km</span>
        </div>
        <div class="workout__details">
        <span class="workout__icon">⏱</span>
        <span class="workout__value">${workout.duration}</span>
        <span class="workout__unit">min</span>
        </div>
        
    `;

    if (workout.type === "running") {
      htmlWorkout += `
            <div class="workout__details">
            <span class="workout__icon">⚡️</span>
            <span class="workout__value">${workout.pace.toFixed(1)}</span>
            <span class="workout__unit">min/km</span>
            </div>
            <div class="workout__details">
            <span class="workout__icon">🦶🏼</span>
            <span class="workout__value">${workout.cadence}</span>
            <span class="workout__unit">spm</span>
            </div>
        </li>
        `;
    }
}

```

**Comment by Monokai** [comment]
This is due to bracket pair colorization. This is one of the reasons I recommend turning bracket pair colorization off. It adds visual noise where it doesn't really solve anything here. I can understand it helps in languages that are bracket heavy, but JavaScript generally doesn't have to be.
