### ISSUE TITLE
How to enable monokai Pro Icons for new file associations?

### ISSUE THREAD

**Issue by Leviathan91** [Monokai/monokai-pro-vscode#351]
I'm using VSCode.
In my tailwind projects, for IntelliSense to work properply, I include this in `.vscode/settings.json` : 
```
"files.associations": {
    "*.css": "tailwindcss"
  }
  ```
 
This leads to .css files not having the monokai css icon anymore. How to apply them again?
I am guessing to add an icon path somewhere, but I don't know how monokai-pro is structured.

**Comment by Monokai** [comment]
I've mapped `tailwindcss` to the css icon in 1.2.1
