### ISSUE TITLE
Possibility to add file icons

### ISSUE THREAD

**Issue by Maxito7** [Monokai/monokai-pro-vscode#354]
More than an issue this is more a type of request. Would it be possible to have a file icon next to the down-pointing arrow? I feel like it would greatly complement the look of the icons overall and have it all feel more complete.

![image](https://user-images.githubusercontent.com/77021922/230989396-9ac68172-6f48-4a97-bf80-1e13c582175b.png)

**Comment by Monokai** [comment]
Different icons make sense for files, because they can contain different types of content. But folders are always folders, I'd like them to be minimal as to not visually clutter the workspace more.

**Comment by Maxito7** [comment]
Yeah I get that is what you're going for. Thanks for providing your reasoning for it tho! :)
