### ISSUE TITLE
Bad contrast colors in all variants in popups (vscode)

### ISSUE THREAD

**Issue by sztomi** [Monokai/monokai-pro-vscode#355]
This is the "filter machine" variant, but all four looks similar (see the highlighted item in the popup which is almost unreadable):

![image](https://user-images.githubusercontent.com/240594/232803017-0c2bb059-9fdb-4afb-980c-5a258496f39b.png)

The same in the Tokyo Night theme:

![image](https://user-images.githubusercontent.com/240594/232803288-11c67eb0-0b19-42cb-aa72-3e92c0b07fa3.png)

It almost seems like the text color is not set by either theme, but the selection background is. I don't know if this is related to Rust Analyzer itself which provides the completion, but I think this popup shows up via the LSP integration. Any way to fix this?

**Comment by sztomi** [comment]
@Monokai ?

**Comment by Monokai** [comment]
I'm seeing this (same for other filters):

<img width="504" alt="Screenshot 2023-05-03 at 07 49 09" src="https://user-images.githubusercontent.com/277589/235840781-fb296bc2-b45c-4cf3-b3be-81b64b1a9cb4.png">

The white color controlled by the `editorSuggestWidget.highlightForeground` property.

Do you have an override color in your user workbench settings perhaps?

**Comment by sztomi** [comment]
Thanks for your reply - it turns out I did have a bunch of overrides for some reason (I don't remember setting them). Removed and all looks good!
