### ISSUE TITLE
I bought the pro version but I keep getting charged

### ISSUE THREAD

**Issue by JanUrbanNeto** [Monokai/monokai-pro-vscode#356]
How to solve this issue?

**Comment by bronlund** [comment]
Cancel the CC :D

**Comment by Monokai** [comment]
Can you please email me with your transaction details (hello at monokai.pro)? Monokai Pro is certainly not an ongoing subscription.

**Comment by tizedboy** [comment]
is the license for lifetime?

**Comment by JanUrbanNeto** [comment]
Yes, it is!


*______________________Jan Urban Neto*
*+55 51 99297-2763*




Em sáb., 10 de jun. de 2023 às 19:12, tizedboy ***@***.***>
escreveu:
