### ISSUE TITLE
CSS animation keyframe syntax color problem

### ISSUE THREAD

**Issue by smlombardi** [Monokai/monokai-pro-vscode#358]
As you can see, the last value in a keyframe with multiple values (i.e. 90% here ) is colored differently and italicized for no reason

<img width="383" alt="Code-20230503_153919" src="https://user-images.githubusercontent.com/835148/236027844-b3b2e783-cbe6-4872-b4e3-2be3cdf36158.png">

Monokai Pro 1.2.1, Mac, VSCode Version: 1.77.3

**Comment by Monokai** [comment]
This is an issue with the VSCode CSS tokenizer. It doesn't capture the first two values correctly, so syntax highlighters can't color those differently.
