### ISSUE TITLE
Add Handlebars icon

### ISSUE THREAD

**Issue by hex20** [Monokai/monokai-pro-vscode#36]
I've been using this theme for a while and loving it. But the lack of a Handlebars icon is a real pain when working on Ember projects. If the theme was open source it would submit a pull request myself.

**Comment by alanaasmaa** [comment]
You could also use temporary some other icon theme.

CTRL+SHIFT+P => File icon theme

**Comment by Monokai** [comment]
Added in 1.1.5

**Comment by hex20** [comment]
Looks great, thanks.
