### ISSUE TITLE
Add background for items with focus (file explorer and dropdowns)

### ISSUE THREAD

**Issue by alinnert** [Monokai/monokai-pro-vscode#37]
I haven't been a big fan of highlighting focused items through text color only. But I thought it's okay-ish enough.

But now that VS Code uses text color to indicate the status of files in an scm repository it's technically impossible to see where my keyboard focus is in the file explorer if the file has any status flag. Can you please add a background color for focused items? I'd also like to have a background color in the drop downs for consistency.

**Comment by medoingthings** [comment]
Big daily issue for me, too. For now I help me out by manually editing the theme configuration. But it’s gone with every update :-/

**Comment by tomepejo** [comment]
Probably `list.inactiveSelectionBackground` should e set.

**Comment by Waldemar-Dassler** [comment]
Work form me
```
  "workbench.colorCustomizations": {
        "focusBorder": "#211c1c",
        "list.focusBackground": "#3a2f2f",
    },
```

**Comment by tomepejo** [comment]
I have added this:
```
    "workbench.colorCustomizations": {
        "list.activeSelectionBackground": "#2B292D",
        "list.inactiveSelectionBackground": "#2B292D"
    }
```
Since I am using Monokai Pro (Filter Spectrum). Works great.

**Comment by Waldemar-Dassler** [comment]
I forgot and add this for selected list element 
```
"list.activeSelectionBackground": "#2B292D",
```

Full fix
```
"workbench.colorCustomizations": {
        "list.activeSelectionBackground": "#2B292D",
        "list.activeSelectionBackground": "#2B292D",
        "list.inactiveSelectionBackground": "#2B292D"
}
```

focus border this line disable white border in the explorer

**Comment by Monokai** [comment]
Added this in 1.1.7
