### ISSUE TITLE
TypeScript generic type arguments are highly affected by whitespace and other irrelevant context

### ISSUE THREAD

**Issue by lionel-rowe** [Monokai/monokai-pro-vscode#372]
**Examples:**

Declaring a function signature with generics seems to be pretty robust to changes in whitespace and surrounding context, but _passing_ type arguments is extremely brittle.

![image](https://github.com/Monokai/monokai-pro-vscode/assets/26078826/1772b924-ddc6-4b3c-94a7-c0ac0910fb32)

Expected:
* `abc` to be consistently green (3/16)
* `<>` to be consistently gray (3/16)
* `()` to be consistently gray (8/12)
* `X`, `Y`, `Z` to be consistently blue (3/8)
* `1`, `2`, `3` to be consistently purple (6/8)

**Code:**

```
declare function abc<A, B, C>(): unknown

const abc2 = abc<1, 2, 3>
const abc3 = abc<X, Y, Z>
const abc4 = abc<
	1,
	2,
	3
>
const abc5 = abc<
	X,
	Y,
	Z
>

const result1 = abc<1, 2, 3>()

const result2 = abc<
	1,
	2,
	3
>()

const result3 = abc<X, Y, Z>()

const result4 = abc<
	X,
	Y,
	Z
>()

const arr = [
	abc<1, 2, 3>(),
	abc<
		1,
		2,
		3
	>(),
	abc<X, Y, Z>(),
	abc<
		X,
		Y,
		Z
	>(),
]

const obj = {
	result1: abc<1, 2, 3> (),
	result2: abc<
		1,
		2,
		3
	>(),
	result3: abc<X, Y, Z>(),
	result4: abc<
		X,
		Y,
		Z
	>(),
}
```

**Comment by Monokai** [comment]
Color schemes depend on syntax definitions to give colors to different tokens. In this case, the token of `abc` with linebreaks is not correctly recognized as a function call. Unfortunately color schemes like Monokai Pro can't color those correctly. Best to take it up with the TypeScript package.
