### ISSUE TITLE
Java Import Colors

### ISSUE THREAD

**Issue by devondragon** [Monokai/monokai-pro-vscode#374]
Revisiting #243  - perhaps this is no longer the case?  Most of the other themes I have been using color the "import" keyword separately from the import class portion (see attached screenshot).

![Screenshot 2023-09-09 at 6 36 53 PM](https://github.com/Monokai/monokai-pro-vscode/assets/1254537/4d2bd518-b997-4595-84c3-eff944e7a16a)

I would love to see this in Monokai Pro, as the all red lines are a bit jarring and make me think there is an error.  Thanks!

**Comment by Monokai** [comment]
Well `import` is a keyword, like `return` or `if` or `export`. I think it's fine as it is.

**Comment by devondragon** [comment]
Right, but the class to import is NOT a keyword.  So it shouldn't look the same.
This is what is looks like in Monakai Pro:

![Screenshot 2023-12-20 at 9 10 06 AM](https://github.com/Monokai/monokai-pro-vscode/assets/1254537/52acb4fb-7788-4d34-bbea-e3c0edd531b0)

Versus the other theme above, where you can clearly see the import keyword as distinct from the package and class.  

You think it's better from a UI/UX perspective to be all the same color?

**Comment by Monokai** [comment]
Ah I see, I agree that's indeed too much, I didn't see it was Java and thought it was JavaScript. I'll update for this.

**Comment by devondragon** [comment]
@Monokai  - Looks like it's fixed in the latest update. Thank you very much!
