### ISSUE TITLE
No License Key received

### ISSUE THREAD

**Issue by linuxgeek55** [Monokai/monokai-pro-vscode#375]
Purchased a PRO license (I have PAYPAL TRANSACTION etc etc) but now follow up email was received with license key

**Comment by johnypony3** [comment]
found this [comment](https://github.com/Monokai/monokai-pro-vscode/issues/336#issuecomment-1373342672)

**Comment by sabarnett** [comment]
I’ve had the same problem. So far, emails to monokai have gone unanswered.

**Comment by johnypony3** [comment]
@sabarnett please read this [comment](https://github.com/Monokai/monokai-pro-vscode/issues/336#issuecomment-1373342672)
