### ISSUE TITLE
No color for "console" in JS

### ISSUE THREAD

**Issue by marvelous06** [Monokai/monokai-pro-vscode#379]
![3](https://github.com/Monokai/monokai-pro-vscode/assets/23704459/8a6a52ff-b9ba-4e36-8ad8-f7829b85efbc)
Tired of watching "console" has the same color with variables after latest update in v1.2.1. Need a fix please. Appreciated.

**Comment by TrpimirTomasic9** [comment]
Same here. Did you manage to fix it?

**Comment by marvelous06** [comment]
> Same here. Did you manage to fix it?

Nope. I turned back to the classic theme :)

**Comment by Monokai** [comment]
You can enable this if you turn on semantic highlighting
