### ISSUE TITLE
Wrong terminal.ansi colors

### ISSUE THREAD

**Issue by ch4r-ch4r** [Monokai/monokai-pro-vscode#384]
Both `terminal.ansiBlue` and `terminal.ansiBrightBlue` are actually orange colors, so we should end up with `terminal.ansiOrange` and `terminal.ansiBrightOrange`

<img width="353" alt="image" src="https://github.com/Monokai/monokai-pro-vscode/assets/78950093/e57978f0-502b-4da3-a7b8-1d16fa8c65ca">

**Comment by Monokai** [comment]
In Monokai Pro there's no blue, only cyan. To have a bit more differentiation and to complete the color spectrum, I opted for this solution.
