### ISSUE TITLE
Better color to distinguish enabled and disabled extensions

### ISSUE THREAD

**Issue by ngocphamm** [Monokai/monokai-pro-vscode#39]
Right now I think it's pretty hard to tell apart.

<img width="291" alt="2017-12-14 at 4 29 pm" src="https://user-images.githubusercontent.com/395123/34015270-f0f6e392-e0eb-11e7-8ff9-e98bb7237dca.png">

**Comment by Monokai** [comment]
I think VSCode made some adjustments in the meantime, so they look more disabled.
