### ISSUE TITLE
License key restore

### ISSUE THREAD

**Issue by gio213** [Monokai/monokai-pro-vscode#390]
Hi,  unexpected I deleted license key from my  email inbox , how is possible to restore it ?

**Comment by StfBauer** [comment]
I have the same issue.

**Comment by rhysbeynon** [comment]
I wouldn't reccomend it, but [https://github.com/maximilionus](Maximilionus) has a tool that you can use to recover your key. Only recover using an email address that has been granted a valid license.

**Comment by StfBauer** [comment]
My Issue got solved already. I got an email.

**Comment by Valium007** [comment]
hello i accidentally deleted the email too, can i get my key?

**Comment by Monokai** [comment]
please mail all license questions to the hello at monokai dot pro.
