### ISSUE TITLE
Support ESLint Icon For ".cjs" Extension Not Only ".js"

### ISSUE THREAD

**Issue by Barzi-Ahmed** [Monokai/monokai-pro-vscode#396]
Hi, 

Unfortunately ESLint only shows for ".eslintrc.js", it doesn't show icon for other types like ".eslintrc.cjs", please support all types of ESLint config extensions, like .eslintrc.cjs, .eslintrc.mjs, .eslintrc.ts, .eslintrc.json, etc.

**Comment by Monokai** [comment]
fixed in 1.3.0
