### ISSUE TITLE
AdonisJS Framework Icons

### ISSUE THREAD

**Issue by cempack** [Monokai/monokai-pro-vscode#398]
Could you please add icons for [AdonisJS](https://adonisjs.com).
As you can see currently Adonis Files look like regular js and ts files.
![Screenshot](https://github.com/Monokai/monokai-pro-vscode/assets/73651345/0a964fa2-2f73-4904-a59d-fc2770408293)

**Comment by Monokai** [comment]
I've added an AdonisJS icon in 1.3.0

**Comment by cempack** [comment]
> I've added an AdonisJS icon in 1.3.0

Thank you :)
