### ISSUE TITLE
Mocha output is difficult to read in the terminal

### ISSUE THREAD

**Issue by Tyriar** [Monokai/monokai-pro-vscode#4]
<img width="513" alt="screen shot 2017-08-21 at 10 21 06 am" src="https://user-images.githubusercontent.com/2193314/29530840-82b841f0-865a-11e7-99cd-401bed7b353b.png">

**Comment by Monokai** [comment]
Is this fixed now? It should be I think :)

**Comment by Tyriar** [comment]
Yep, fixed :+1:
