### ISSUE TITLE
Is it possible to add a single licence per color scheme?

### ISSUE THREAD

**Issue by Jcrs** [Monokai/monokai-pro-vscode#40]
Hi there, 

I'm currently evaluating this and loving it! Great work!

However, I've a simple request/idea: Would it be possible to add a single licence per color scheme and icons ? 

I like the color variations but, to be honest, personally, I don't think I'd use any other color scheme other than Monokai Pro. And I don't think I'd spend 10€ for just one color scheme. But I'd gladly pay 2.5€/3€ for just that one! 

Thanks!

**Comment by Monokai** [comment]
Thanks for the suggestion. That would be too much overhead on my part I'm afraid. I would have to maintain different packages, and update each and every package. Of course parts could be automated, but one package keeps things more manageable I think.
