### ISSUE TITLE
Which is the font in the screenshot

### ISSUE THREAD

**Issue by GuillaumeNachury** [Monokai/monokai-pro-vscode#41]
Hi,
Can you tell me which the font used in the snapshot on the website 

![Fonts](https://www.monokai.pro/assets/img/vscode/cd8d292a.png)

Should the font be part of the theme ?

Thx,
G.

**Comment by ngocphamm** [comment]
Operator Mono. $200 font. https://www.typography.com/fonts/operator/styles/

**Comment by ntwb** [comment]
FYI: I use the free *Input* with the "Source Code Pro" preset style http://input.fontbureau.com

**Comment by balls-6g** [comment]
you can try "Maple Mono" on [github repo](https://github.com/subframe7536/maple-font), its good
