### ISSUE TITLE
Highlight PHPDock types also typed in lowercase (string, int etc..)

### ISSUE THREAD

**Issue by alanaasmaa** [Monokai/monokai-pro-vscode#42]
Currently it paints only typed `Int`, `String` etc.. but in php dock you will write all lowercase. So it would be nice to Highlight them too.

![image](https://user-images.githubusercontent.com/12788337/34198448-19267a72-e573-11e7-982b-a527a7a52b6f.png)

**Comment by Monokai** [comment]
I think this has more to do with syntax definitions than with the color scheme. The syntax definitions probably don't parse lowercase words.
