### ISSUE TITLE
Activity Bar icons invisible in "Top" and "Bottom" positions for light theme

### ISSUE THREAD

**Issue by C0Nd3Mnd** [Monokai/monokai-pro-vscode#420]
This is how it (correctly) looks in the "Default" position:

![image](https://github.com/user-attachments/assets/af686067-6d9b-4cad-8071-7ae4d7364f99)

And this is how it looks like in the "Top" position:

![image](https://github.com/user-attachments/assets/3dd9b175-ff2f-4457-8b28-d25d90007b47)

As you can (or can't) see, the icons are invisible. This applies to "Monokai Pro Light" and "Monokai Pro Light (Filter Sun)". It works fine with the dark theme:

![image](https://github.com/user-attachments/assets/a57ab2e8-0af5-42d0-b93a-c4c6b45214c2)

**Comment by Monokai** [comment]
Fixed in 2.0.1
