### ISSUE TITLE
Android Studio and IntelliJ IDE Support?

### ISSUE THREAD

**Issue by roguearch** [Monokai/monokai-pro-vscode#43]
is there any way to apply this theme to android studio or any intellij ide?

**Comment by Monokai** [comment]
Not yet. It's on my list, but I'm maintaining this in between other work :)

**Comment by DuncanHills** [comment]
I and a good number of other Twitter developers would certainly use an IntelliJ IDEA theme since it is our primary IDE.

**Comment by ccpost** [comment]
I would really love this as well. When I switch from Sublime (w/ Monokai Pro) to GoLand for debugging the difference is harsh. :-)

**Comment by Monokai** [comment]
I simply cannot find the time at the moment. Closing for now.
