### ISSUE TITLE
Purchase of license

### ISSUE THREAD

**Issue by laugustofrontend** [Monokai/monokai-pro-vscode#44]
Good afternoon, I would like to know if I have to buy a **license** for **sublime** and another for **vscode** or I can use the same license for the 2 publishers?

**Comment by ntwb** [comment]
Yes you do, see also https://github.com/Monokai/monokai-pro-vscode/issues/33

**Comment by Monokai** [comment]
Correct!

**Comment by ehsaanhridoy** [comment]
[VSCode] How to obtain MonokaiPRO for free
Guide

What you need
VSCode
Internet Connection

Tested on MAC OS X & Windows
How to install free for Visual Studio Code:
Extensions > Search for 'Monokai Pro' > Install
Command Palette > Monokai Pro: select theme
Now hack 'em all!
go to extension folder

Linux / MAC OS
cd ~/.vscode/extensions/monokai.theme-monokai-pro-vscode<version>

Windows
cd %USERPROFILE%\.vscode\extensions 

2. Open /js/app.js
code /js/app.js
3. Beautify it
4. Find key: "isValidLicense",
5. Change return statement
`return !(!e || !t) && t === (0, n.default)("" + a.default.APP.UUID + e).match(/.{1,5}/g).slice(0, 5).join("-")`
to
`return true`
6. Close and Reopen VSCode
