### ISSUE TITLE
PHP "close tag" missing syntax highlight?

### ISSUE THREAD

**Issue by vinnlee** [Monokai/monokai-pro-vscode#47]
![issue](https://user-images.githubusercontent.com/20036316/34856549-3b5b49c6-f778-11e7-9110-53188598825e.png)

**Comment by robcapac** [comment]
![screen shot 2018-03-21 at 6 56 57 pm](https://user-images.githubusercontent.com/13685078/37741903-beda2726-2d39-11e8-8eb1-c9e45dc63401.png)

Same here...please fix.

**Comment by Monokai** [comment]
Fixed in 1.1.6
