### ISSUE TITLE
closing script tag - first character is white

### ISSUE THREAD

**Issue by events-jonas-chrisw** [Monokai/monokai-pro-vscode#48]
See here:

![screenshot 2018-01-19 12 24 36](https://user-images.githubusercontent.com/33231747/35150856-ee3e763a-fd13-11e7-97fc-e14b69dc7802.png)

**Comment by jasperjorna** [comment]
Same problem with Laravel Blade syntax.

<img width="412" alt="screen shot 2018-02-19 at 19 16 20" src="https://user-images.githubusercontent.com/903653/36392011-74f7eca8-15a9-11e8-843b-03be3a6a64e3.png">

**Comment by Monokai** [comment]
Fixed in 1.1.6
