### ISSUE TITLE
Xcode

### ISSUE THREAD

**Issue by BAndonovski** [Monokai/monokai-pro-vscode#50]
Any plans for porting this to Xcode? 
I'm using Xcode, VSCode & Sublime and would love to have the same color scheme on all three.

**Comment by akiekintveld** [comment]
I have a theme I created that tries to match the syntax highlighting of VSCode and Sublime. It'd be great to get an official port though.

**Comment by cdalvaro** [comment]
> I have a theme I created that tries to match the syntax highlighting of VSCode and Sublime. It'd be great to get an official port though.

Could you share your theme, please?
