### ISSUE TITLE
Text selected in output window is not highlighted

### ISSUE THREAD

**Issue by code2play** [Monokai/monokai-pro-vscode#53]
As the GIF describes, the text I selected is not highlighted.
It's quite annoying when I try to select text in the output window.
Hope this can be fixed soon.
![animation](https://user-images.githubusercontent.com/25173473/36429827-a21cc84e-168e-11e8-8c77-88cfab7ae2f2.gif)

**Comment by Monokai** [comment]
This is strange and I'm seeing the same thing. Definitely not intended, but I can't find the setting to enable this.

**Comment by Monokai** [comment]
Checked again and it seems to be fixed
