### ISSUE TITLE
Please add a "Workspace" icon

### ISSUE THREAD

**Issue by ntwb** [Monokai/monokai-pro-vscode#58]
As documented here: https://code.visualstudio.com/docs/editor/multi-root-workspaces#_editor :
> _"If you are using an Icon Theme and the active theme supports it, you will see a special Workspace icon."_
>
> _"Below you can see the Workspace icons from the built-in Minimal (Visual Studio Code) icon theme"_

**Comment by Monokai** [comment]
Added in 1.1.7
