### ISSUE TITLE
Static classes in PHP not rendering correctly

### ISSUE THREAD

**Issue by brnmonteiro** [Monokai/monokai-pro-vscode#59]
Bug: When static class name is camelCase, the theme don't renderize correctly.

Screenshot in attachment

![captura de tela 2018-03-15 as 22 54 57](https://user-images.githubusercontent.com/6596579/37499719-fd53292a-28a3-11e8-9e72-d8ae22fd6dca.jpg)

**Comment by Monokai** [comment]
I think this is more of a syntax definition problem that a syntax highlighting problem. I unfortunately don't have control over the syntax definitions with Monokai Pro.
