### ISSUE TITLE
Panel dropdown feedback

### ISSUE THREAD

**Issue by Tyriar** [Monokai/monokai-pro-vscode#6]
It's difficult to see that it's a dropdown due to lack of a background color

<img width="191" alt="screen shot 2017-08-21 at 10 26 47 am" src="https://user-images.githubusercontent.com/2193314/29530983-4c287f14-865b-11e7-9d6c-82aca2248c47.png">

**Comment by Monokai** [comment]
Fixed in 1.1.0
