### ISSUE TITLE
Is license per machine or per user?

### ISSUE THREAD

**Issue by isteven** [Monokai/monokai-pro-vscode#60]
Hi, as per title, is the license per machine or per user? 

Meaning, if I have VS Code with Monokai Pro at home & at work, do I have to pay for two, or one is enough?

**Comment by FLeXyo** [comment]
> Any person who has purchased a license from Monokai is
granted use of Monokai Pro on any number of computers that belongs to that
person.

Source: https://monokai.gallerycdn.vsassets.io/extensions/monokai/theme-monokai-pro-vscode/1.1.5/1514729607115/Microsoft.VisualStudio.Services.Content.License

**Comment by Monokai** [comment]
That is correct. Any person who has purchased a license from Monokai is granted use of Monokai Pro on any number of computers that belongs to that person.
