### ISSUE TITLE
Tabs too prominent

### ISSUE THREAD

**Issue by smlombardi** [Monokai/monokai-pro-vscode#61]
FWIW, I added this override to make the tabs make more sense to me:

```
  "workbench.colorCustomizations": {
    "[Monokai Pro (Filter Machine)]": {
      "tab.activeBorder": "#273136",
      "tab.activeForeground": "#ffffff",
      "tab.inactiveBackground": "#1d2528",
      "tab.border": "#161b1e",
      "editorGroupHeader.tabsBackground": "#1d2528"
    },
  },
```
I found the bright gold text too distracting, and the gold bottom-border was too close to the first line of code.

<img width="428" alt="screen shot 2018-04-02 at 3 08 34 pm" src="https://user-images.githubusercontent.com/835148/38211207-bba28c22-3687-11e8-9b2d-4d7286793a4b.png">

**Comment by Monokai** [comment]
I dimmed those a bit in 1.1.6
