### ISSUE TITLE
Syntax highlighting bug in HTML files

### ISSUE THREAD

**Issue by Kirlovon** [Monokai/monokai-pro-vscode#62]
Hi, 
When you inserting **style** or **script** tags in HTML files, something strange is happening with highlighting: ![Imgur](https://i.imgur.com/kj3d2IM.png)

When you closing this tags, left angle bracket becomes white! It seems to be a trifle, but when you frequent write HTML code, it becomes torture! I'm ready to buy this theme, but please, fix it! 🙏

**Comment by Monokai** [comment]
Fixed in 1.1.6
