### ISSUE TITLE
Licensing is useless. (no troll post, i promise)

### ISSUE THREAD

**Issue by itsacorn** [Monokai/monokai-pro-vscode#64]
Right. At first, you might think that licensing a theme that's this good only makes sense. But it doesn't. The license checking stuff is all inside of a JS file, and guess what, of course you can replace a few statements with `true` and you dont get the "Purchase Monokai Pro" messages anymore. Maybe obfuscation could help? In my opinion, it makes no sense to have a licensing system that can be disabled by changing a few lines of plain JS.

**Comment by rynstwrt** [comment]
You can also make one of the txt files inside the package's (I forgot, I use Atom now) permission to be read only after changing the last check to -1 or something.

**Comment by itsacorn** [comment]
Well, i'm not trying to collect as many licensing bypasses in one issue, i'd just be happy if the developer would make it a little more secure. He deserves the money as this is a truly amazing theme. I've tried Ristretto, Octagon and Pro so far, and i like them all as much as no other theme.

**Comment by Monokai** [comment]
While the licensing mechanism may be useless technically, morally I think it's not.

I'm open to other solutions, but there are costs to make it more secure. A more secure alternative is having a remote server that stores some of your personal information and letting the editor phone home every once in a while. I think that's overkill and I don't want to go that way. I could also consider monthly subscriptions (…kidding). I think this solution is quick, requires no remote personal information storage and is, above all, fair.

It all boils down to this. I put in time to make a theme, you pay a premium if you want to support it and / or want to get rid of the pop-ups. Everybody happy :)

**Comment by rich-poole** [comment]
In my experience, the people who will try to bypass paying for a theme are very unlikely to buy it as they will just try to find a free alternative anyway.

I just paid, thanks for the great theme :)

**Comment by kedwin** [comment]
anybody who wants to bypass it is really desperated, it is really cheap, just check how many hours you waste trying to found some theme for your eyes, now calculate those hours how much money could you make while working not wasting time searching for a theme.

payed without thinking

**Comment by MacKentoch** [comment]
Thank you @Monokai just changed from Nord theme to Monokai PRO and paid to express my gratitude and encourage you.

**Comment by pzmosquito** [comment]
Why do you even look into how to bypass it in the first place? Sure, it's simple JS, but even with a more secured registration/validation, it can also be bypassed. If people don't want to pay $10, they will find a way. Microsoft can't prevent it, Apple can't prevent it. If people appreciate the work, they will pay, it's simple as that

**Comment by Rohaq** [comment]
> Why do you even look into how to bypass it in the first place? Sure, it's simple JS, but even with a more secured registration/validation, it can also be bypassed. If people don't want to pay $10, they will find a way. Microsoft can't prevent it, Apple can't prevent it. If people appreciate the work, they will pay, it's simple as that

I think he's just bringing it up as a possible concern that _could_ potentially be addressed technically.

But as has already been discussed: It would end up being initially successful - at least until someone cracks it, at which point it would need fixing to make effective again, repeat a few times, and this feature ends up taking far too much maintenance for a feature that's only temporarily successful - all over blocking access to people who likely would never have paid for a license anyway.

**Comment by nblackburn** [comment]
It's a lost cause trying to make this more secure as proven time and time again. If someone wants to bypass this then they will.

**Comment by xmaxrayx** [comment]
imagine buy 10$ to a theme when I can buy a whole program "clip studio paint" with that price, you guys love flixing you are ritchkid.
