### ISSUE TITLE
PHP syntax highlight issue

### ISSUE THREAD

**Issue by rcapac** [Monokai/monokai-pro-vscode#66]
![screen shot 2018-05-01 at 3 19 33 pm](https://user-images.githubusercontent.com/13685078/39489338-1f138748-4d53-11e8-8b55-0573346e5b9b.png)

bracket on the very bottom is not uniform  with the rest of the code....please fix.

**Comment by Monokai** [comment]
This is probably an issue with the syntax definitions, and not so much with highlighting.
