### ISSUE TITLE
Pay button doesn't work for me

### ISSUE THREAD

**Issue by Ulizzz** [Monokai/monokai-pro-vscode#67]
Hi!
First of all thank you for the wonderful font that I really enjoy using. I, as many others, believe it is worth the price, so I would like to buy it for my vscode. The issue is, when I press the 'buy' button nothing happens, so I cannot complete the purchase. I'm on mac os and my web browser is chrome. Pls advise.

**Comment by kilgarenone** [comment]
For me it's the 'Continue Shopping' button - i click it and it just closes the whole modal..

**Comment by Monokai** [comment]
That is weird, as I'm using a standard checkout script. Anybody else having this problem?

**Comment by 4l3x4ndr3** [comment]
Hello,
Thank you for your awesome theme, I bought it for vscode and sublime but I received 2 times the confirmation and instructions for Sublime.
What are the instructions for vscode in order to activate the licence ?
