### ISSUE TITLE
[Icon Request] .npmignore

### ISSUE THREAD

**Issue by GU5TAF** [Monokai/monokai-pro-vscode#70]
Hi, would love an icon for .npmignore files.
Perhaps it could be used for package.json as well, but that's a bit of a philosophical question as it's just a json file, the json icon also makes a lot of sense.

Went ahead and created two based on the grid you seem to use, feel free to use them if you think they're up to the task.

![npm](https://svgshare.com/i/6Yn.svg)
![npm](https://svgshare.com/i/6_j.svg)

**Comment by GU5TAF** [comment]
No problem, thanks for adding it!

**Comment by doctorsirius** [comment]
This issue should be closed
