### ISSUE TITLE
Monochrome file icons themes revert to normal if user settings file is modified

### ISSUE THREAD

**Issue by doctorsirius** [Monokai/monokai-pro-vscode#72]
If you set a monochrome file icon theme by using the settings menu on the activity bar and then you modify the user settings file from Preferences (F1) the "workbench.iconTheme": settings is reset to default (colored) icon theme.

**Comment by VincEnterprise** [comment]
Have you set `monokaiPro.fileIconsMonochrome` to true?

**Comment by doctorsirius** [comment]
Nop, I didn't even know that existed, but if you provide a menu to change the icons to monochrome and that action introduces **`"workbench.iconTheme": "Monokai Pro (Filter Octagon) Monochrome Icons"`** on user settings, why not add **`"monokaiPro.fileIconsMonochrome": true`**, at the same time?

**Comment by VincEnterprise** [comment]
Ya thats why you keep `monokaiPro.fileIconsMonochrome` in your settings so you're icon theme selection doesn't get overwritten.
