### ISSUE TITLE
Paid for a licence, didn't get it

### ISSUE THREAD

**Issue by ValdoGhafoor** [Monokai/monokai-pro-vscode#76]
Hello ! 
I bought a VSCode license 3 days ago and didn't receive the confirmaton email nor the license.
I paid via paypal
Can I have help for this ? It's a bit frustrating.
I love your theme but I don't want to live one more day on this earth seeing that startup popup

<img width="646" alt="capture d ecran 2018-06-02 a 10 01 08" src="https://user-images.githubusercontent.com/7875009/40872278-e5937dea-664b-11e8-94fc-f75a3f667588.png">

**Comment by Monokai** [comment]
I understand that's frustrating. You should have got an email automatically, right away. Can you please mail me your paypal transaction ID to hello at monokai.pro? We'll sort it out.

**Comment by ValdoGhafoor** [comment]
Thanks for your help, my issue has been solved

**Comment by akmalhakimi1991** [comment]
Sorry for bumping this old issue but I have a similar problem. Bought a license for VS Code version but no email been sent. Tried to reach out hello at monokai.pro but Gmail said:

> The recipient server did not accept our requests to connect. Learn more at https://support.google.com/mail/answer/7720 [monokai.pro. 188.166.30.68: generic::failed_precondition: connect error (111): Connection refused]

**Comment by Monokai** [comment]
Do you by any chance have a Yahoo address? They seem to be complaining about my domain. Can you please send an email to hello at monokai.nl so we can resolve this?

**Comment by akmalhakimi1991** [comment]
@Monokai Yeah I'm using Yahoo mail. However, I already received the license a few hours ago.

**Comment by markslingerland** [comment]
Sorry for bumping this issue again, but I have seem to run into the same problem with not receiving any email, I purchased it last friday and have yet to receive a code. Could you help me further?

**Comment by MajkaBoo** [comment]
Hi,  I purchased the upgrade for Monokai Pro license on February 12th via PayPal 
(Transaktion number: 7H475453RU767843T) and I still haven't received the activation number. 
My VSC keeps asking to upgrade. Please advice.
