### ISSUE TITLE
[Icons Request] .erl (erlang) .beam (vm compiled)

### ISSUE THREAD

**Issue by areel** [Monokai/monokai-pro-vscode#78]
Doing Erlang and Elixir coding.
Would be nice to have an icon for ".erl" files (Erlang) and ".beam" files (erlang virtual machine compiled files)
Pass the love on from Elixir.

The .beam file icon would be applicable to Elixir projects as well, so 2 for 1.

**Comment by Monokai** [comment]
Added erlang icon in 1.1.7, .beam files are compiled and for now I don't plan to add icons for those.
