### ISSUE TITLE
Font Family used

### ISSUE THREAD

**Issue by p4pramod** [Monokai/monokai-pro-vscode#83]
Hi,
The font you have used in the example is fabulus. It will be great if you let me know the font family name
thanks
Pramod

**Comment by StanleySathler** [comment]
Hello @p4pramod 👋 
The font used is the _Operator Mono_. Unfortunately, that is not a free font.

**Comment by himhimlo** [comment]
You may want to use Dank Mon instead. It's great and has an affordable price.

**Comment by sgarcia-dev** [comment]
Old thread, I know...but how would one enable Dank Mono on this theme?
