### ISSUE TITLE
Excesive dimming of the filter box on problems tab

### ISSUE THREAD

**Issue by doctorsirius** [Monokai/monokai-pro-vscode#93]
Monokai themed version
![image](https://user-images.githubusercontent.com/28984901/45086537-a3725f00-b103-11e8-8813-7b0507c1f294.png)
The text is difficult to read

VS Code Dark Theme
![image](https://user-images.githubusercontent.com/28984901/45086560-bc7b1000-b103-11e8-8ad2-c72486090931.png)

**Comment by fgb4101** [comment]
**Version: 1.1.12**
![monokai search box 2019-03-27_170105](https://user-images.githubusercontent.com/14864288/55112137-43003a80-50b2-11e9-9cae-0c009e23611d.jpg)

Can you please confirm if this is the intended design? 
Looks like the fix did not work or the issue was introduced again.
