### ISSUE TITLE
Checkboxes used on the new preferences page lack styling

### ISSUE THREAD

**Issue by doctorsirius** [Monokai/monokai-pro-vscode#94]
![image](https://user-images.githubusercontent.com/28984901/45208015-da727d00-b289-11e8-8743-fab762277dad.png)

**Comment by himhimlo** [comment]
![ss2](https://user-images.githubusercontent.com/3815971/45408323-a4286980-b69e-11e8-8487-0f663459875a.png)
Same case on the drop down list of the new preferences page too.
