### ISSUE TITLE
how to remove the theme

### ISSUE THREAD

**Issue by heaversm** [Monokai/monokai-pro-vscode#95]
Hi - I want to remove monokai pro. It has been disabled but I still get annoying popups to purchase it every time I start vscode.

**Comment by shandou** [comment]
@heaversm How did you resolve this issue? I am having the same pop up at the moment and would like to disable it. Don't seem to find obvious solutions. Thanks! :)

**Comment by rwz** [comment]
Came here for the same thing. Not sure how to remove the theme and this issues comes up in google. Would be nice to post the solution here.

**Comment by JustEngeneer** [comment]
Hello! Probably this is no longer relevant, but...
File-Preferences-Extensions. Then you should find the icon 'Manage' and you will be able to remove it.

**Comment by rosyvs** [comment]
I have the same issue and following @JustEngeneer's advice I don't see Monokai pro in the list of extensions

**Comment by JustEngeneer** [comment]
To [rosyvs](https://github.com/rosyvs)
Try to install Monokai pro extension and then try to remove it.

**Comment by mohamaadbey** [comment]
Hi. I was changed the icon theme from setting -> appearance and it's worked!!!
