### ISSUE TITLE
License and Source

### ISSUE THREAD

**Issue by brettgilio** [Monokai/monokai-pro-vscode#98]
I did not see any issue history pertaining to this. I love your theme, it is absolutely terrific. I know the monokai family of themes are traditionally free (not necessarily free, as in price) and open source. I am curious why you did not choose to continue this trend.

Best wishes,
Brett

**Comment by FLeXyo** [comment]
[This](https://github.com/Monokai/monokai-pro-vscode/issues/64#issuecomment-385461042) should answer your question.
